### ISSUE TITLE
Teensy 4.0 fails to register subscription to executor with general status error

### ISSUE THREAD

**Issue by coalman321** [micro-ROS/micro_ros_arduino#1031]
- Hardware description: Teensy 4.0
- RTOS: Bare Metal
- Installation type: micro_ros_setup + recompiled version of this library to support custom messages
- Version or commit hash: humble

#### Steps to reproduce the issue

1. Use a local installation of Micro Ros agent to support custom message definitions.
2. Recompile this library to support the same definitions using the docker micro-ros library builder image (the artifacts are below, including the message definitions).
3. Use the following Arduino program below with the re-compiled micro-ros library.
4. Set the following settings on the teensy: dual serial, 816MHz clock, optimize "fast"
6. Connect to an agent over USB serial to the native serial port (generally ttyACM0). Logs go to the next usb serial device (generally ttyACM1).

#### Expected behavior
Teensy is able to establish a session, and register all three subscribers in the code to the executor, and enter an agent connected state. (the colcon.meta file is configured for 5 as the max) 

#### Actual behavior
Teensy can establish the session, but will fail to register the third subscriber (whatever it is, order does not matter) to the executor. It then falls back to waiting for agent to restart the connection attempt. 
If I remove any one of the three subscribers, the connection will establish, and data can begin flowing. 

Example log from the debug port during a connection attempt with all 3 subscribers:
![image](https://user-images.githubusercontent.com/5054270/171449455-20836cef-1e32-4740-9b6a-762f318f6015.png)
[gist from the agent during these attempts](https://gist.github.com/coalman321/baaca6d2ef4394a78c4bc12908a8d30f)

#### Additional information
The specific code can be found here, along with the recompiled version of micro-ros with the message package placed inside the extra packages directory: 
[micro_ros_arduino_patched.zip](https://github.com/micro-ROS/micro_ros_arduino/files/8815873/micro_ros_arduino_patched.zip)
[Teensy code gist](https://gist.github.com/coalman321/454aae8008b012e95480b34727e1d7f8)
(if it does crash or stop after the agent connection succeeds, that is a lack of testing on my end)

I have also tried both static and dynamic allocation for the custom message types. Neither of the dynamic and static allocations made a difference in the outcome of the error. 

Please let me know if you have any suggestions, or need any additional information.

**Comment by pablogs9** [comment]
You are initing the executor with 2 handles here:

```
  RCCHECK(rclc_executor_init(&executor, &support.context, 2, &allocator));
```

and adding 3 entities here:

```
  RCCHECK(rclc_executor_add_subscription(&executor, &pos_loader_sub, &pos_msg, &rcv_position, ON_NEW_DATA));
  RCCHECK(rclc_executor_add_subscription(&executor, &force_loader_sub, &force_msg, &rcv_force, ON_NEW_DATA));
  RCCHECK(rclc_executor_add_subscription(&executor, &header_sub, &header_msg, &rcv_header, ON_NEW_DATA));
```

Just set the handles (3º argument of `rclc_executor_init`) to the number of entities you need to add.
