### ISSUE TITLE
Pinging the agent not working

### ISSUE THREAD

**Issue by Johannap1** [micro-ROS/micro_ros_arduino#1042]
Hardware description: ESP32dev
microros arduino + platformio
Version or commit hash: ROS2 foxy

Hello, 

I had my microros application running successfully, and today I rebuild the Arduino library and suddenly pinging the agent is not working anymore. I did not make any changes regarding the pinging functionality to my own code. So I went ahead and tested the reconnection example again and also there pinging the agent returns an error even though there is a connection. I opened a [similar issue](https://github.com/micro-ROS/micro_ros_arduino/issues/912) a few months ago and it is the same behavior again. I used the new reconnection example. I also tried running it from the docker as was suggested previously and updated my agent which both changes nothing. 

Could you please check if the reconnection example is working for you with the same setup or if there might be an issue with the library update.

Thank you!

**Comment by pablogs9** [comment]
Make sure that you have a recent version of the micro-ROS Agent and a recent version of the micro-ROS client library.

**Comment by pablogs9** [comment]
I have just tested micro-ROS for Arduino library commit 5c61a4d21fa4432818764ae5b9e0340db5fc092d and latest `microros/micro-ros-agent:foxy` micro-ROS Agent image and the example works as expected.

Make sure that you pull the latest docker image: `docker pull microros/micro-ros-agent:foxy`

**Comment by Johannap1** [comment]
Thanks, it is working now!
