### ISSUE TITLE
Publisher does not reconnect to the ROS core if the connection is interrupted

### ISSUE THREAD

**Issue by SpMakris** [micro-ROS/micro_ros_arduino#1066]
I am testing the publisher example on Arduino Due, using an ENC28J60 ethernet module to connect to the ROS2 core, via a router.
If the ethernet cable is plugged in and the ROS2 agent has been started, Arduino, will connect as expected and seems to work properly. Branch used is galactic.
If the connection is interrupted, ie removing the ethernet cable or quitting the ROS2 agent on the computer side, the arduino code will produce a soft error and run the associated code. It will not reconnect to the ROS network, even though ethernet connectivity is brought back up and the peripheral connects to it like it should (by running Ethernet.maintain() regularly).
What is the suggested way of reconnecting a publisher to a ROS core, except for restarting the microcontroller itself? 
How can I check the connection status to the ros network?

**Comment by pablogs9** [comment]
Check the reconnection example: https://github.com/micro-ROS/micro_ros_arduino/blob/humble/examples/micro-ros_reconnection_example/micro-ros_reconnection_example.ino
