### ISSUE TITLE
question about rclc_publisher_init_best_effort()

### ISSUE THREAD

**Issue by z2010012286** [micro-ROS/micro_ros_arduino#1080]
## Issue template

- M5 stack Atom Lite (esp32 core)
- ubuntu 20.04 + ros2 foxy
- micro_ros_arduino

#### Steps to reproduce the issue

Sorry for my poor English..

I try to publish the topic `/turtle1/cmd_vel` from M5stack to ROS2 foxy to control the turtle, and it works well. The turtlesim moves in a correct way. In this case, I used the `rclc_publisher_init_default()` for the reliable communication.

I also found there is another function `rclc_publisher_init_best_effort()` can improve the publish frequency. But when I used the `rclc_publisher_init_best_effort()`, the turtle didn't move! I'm sure the code was complied sucessfully and there was `/turtle1/cmd_vel` topic in the ros2 environment. And the `turtle1/cmd_vel` topic has a correct output that I have checked it using the command `ros2 topic echo /turtle1/cmd_vel`.

1. Start with https://github.com/micro-ROS/micro_ros_arduino/blob/humble/examples/micro-ros_publisher/micro-ros_publisher.ino

2. Change the example code to publish geometry_msgs/msg/Twist as below.

   ```c
   #include <micro_ros_arduino.h>
   
   #include <stdio.h>
   #include <rcl/rcl.h>
   #include <rcl/error_handling.h>
   #include <rclc/rclc.h>
   #include <rclc/executor.h>
   
   #include <geometry_msgs/msg/twist.h>  //changed!
   
   rcl_publisher_t publisher;
   geometry_msgs__msg__Twist msg; //changed!-->modify msg type <twist__struct.h>
   rclc_executor_t executor;
   rclc_support_t support;
   rcl_allocator_t allocator;
   rcl_node_t node;
   rcl_timer_t timer;
   
   #define LED_PIN 27 //changed!-->Modify M5 stack Atom Lite LED pin
   
   #define RCCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){error_loop();}}
   #define RCSOFTCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){}}
   
   void error_loop(){
     while(1){
       digitalWrite(LED_PIN, !digitalRead(LED_PIN));
       delay(100);
     }
   }
   
   void timer_callback(rcl_timer_t * timer, int64_t last_call_time)
   {  
     RCLC_UNUSED(last_call_time);
     if (timer != NULL) {
       RCSOFTCHECK(rcl_publish(&publisher, &msg, NULL));
       
   	static int cnt = 0;
   	msg.linear.x = 0.2;                            //const linear.x
   	msg.angular.z = 1.0 - 0.001*cnt;               //variable angular.z
   	cnt++;
     }
   }
   
   void setup() {
     set_microros_transports();
   
     pinMode(LED_PIN, OUTPUT);
     digitalWrite(LED_PIN, HIGH);  
   
     delay(2000);
   
     allocator = rcl_get_default_allocator();
   
     //create init_options
     RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));
   
     // create node
     RCCHECK(rclc_node_init_default(&node, "micro_ros_arduino_node", "", &support));
   
     // create publisher
     RCCHECK(rclc_publisher_init_best_effort(
       &publisher,
       &node,
       ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Twist),
       "turtle1/cmd_vel"));  //changed!-->modify topic name
   
     // create timer,
     const unsigned int timer_timeout = 1000;
     RCCHECK(rclc_timer_init_default(
       &timer,
       &support,
       RCL_MS_TO_NS(timer_timeout),
       timer_callback));
   
     // create executor
     RCCHECK(rclc_executor_init(&executor, &support.context, 1, &allocator));
     RCCHECK(rclc_executor_add_timer(&executor, &timer));
   
     // changed!-->msg initialization
     msg.linear.x=0;
     msg.linear.y=0;
     msg.linear.z=0;
     msg.angular.x=0;
     msg.angular.y=0;
     msg.angular.z=0;
   }
   
   void loop() {
     delay(100);
     RCSOFTCHECK(rclc_executor_spin_some(&executor, RCL_MS_TO_NS(100)));
   }
   ```

   

3. `ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0`

4. `ros2 run turtlesim turtlesim_node` 

5. the `turtle1/cmd_vel` topic is running normal, but the turtle doesn't move!

6. when I used the `rclc_publisher_init_default()` instead of `rclc_publisher_init_best_effort()`, everything is OK! The turtle is moving! 

#### Expected behavior

The turtle shoule be move in a correct way.

#### Actual behavior

The turtle doesn't move when I used `rclc_publisher_init_best_effort()`. 

However, everyhing is OK when I used `rclc_publisher_init_default()`.

#### Additional information

I use the `rqt_graph` to check the releated topic information, it seems everything is OK. But the turlte doesn't move when I used the function `rclc_publisher_init_best_effort()`.

![image-20220714090416009](https://s2.loli.net/2022/07/14/gBE2hpbUvwnW4yu.png)

It seems that rclc_publisher_init_best_effort() has a bug..

**Comment by pablogs9** [comment]
In general, in ROS a reliable subscription is not compatible with a best effort publisher: https://docs.ros.org/en/rolling/Concepts/About-Quality-of-Service-Settings.html#qos-compatibilities
