### ISSUE TITLE
Building using docker:micro_ros_static_library_builder fails when RCL_LOGGING_ENABLED=ON in colcon*.meta file(s)

### ISSUE THREAD

**Issue by alikureishy** [micro-ROS/micro_ros_arduino#1086]
## Issue template

- Hardware description: ESP32
- RTOS: Arduino
- Installation type: docker
- Version or commit hash: humble

#### Steps to reproduce the issue
**Step 0:**
```
git clone -b humble git@github.com:micro-ros/micro_ros_arduino.git
```

**Step 1:**
Set ```RCL_LOGGING_ENABLED``` to 'ON' under the ```rcl``` section in the ```colcon.meta```/```colcon_lowmem.meta```/```colcon_verylowmem.meta``` files as follows:

```
   ...
        "rcl": {
            "cmake-args": [
                "-DBUILD_TESTING=OFF",
                "-DRCL_COMMAND_LINE_ENABLED=OFF",
                "-DRCL_LOGGING_ENABLED=ON"                     <--------------- SWITCH TO 'ON'
            ]
        },
   ...
```

**Step 2:**
Build the micro_ros_arduino library (libmicroros.a) using the docker image:
```
docker run -it --rm -v $(pwd):/project --env MICROROS_LIBRARY_FOLDER=extras microros/micro_ros_static_library_builder:humble -p esp32
```

#### Expected behavior

Should compile successfully.

#### Actual behavior

```
CMake Error at cmake/get_default_rcl_logging_implementation.cmake:43 (find_package):
  By not providing "Findrcl_logging_spdlog.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "rcl_logging_spdlog", but CMake did not find one.

  Could not find a package configuration file provided by
  "rcl_logging_spdlog" with any of the following names:

    rcl_logging_spdlogConfig.cmake
    rcl_logging_spdlog-config.cmake

  Add the installation prefix of "rcl_logging_spdlog" to CMAKE_PREFIX_PATH or
  set "rcl_logging_spdlog_DIR" to a directory containing one of the above
  files.  If "rcl_logging_spdlog" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:26 (get_default_rcl_logging_implementation)
---
Failed   <<< rcl [1.11s, exited with code 1]
```

#### Additional information

Is there a ROS2 package I'm missing? I looked around for a ```rcl_logging_spdlog``` package for install but couldn't find one.

**Comment by pablogs9** [comment]
`RCL_LOGGING_ENABLED` is not tunable under micro-ROS you should keep this `OFF`. We do not have support for packages such as `rcl_logging_spdlog` since [spdlog](https://github.com/gabime/spdlog) is not easily portable to embedded platforms.
