### ISSUE TITLE
Triggered execution does not work with action server

### ISSUE THREAD

**Issue by metanav** [micro-ROS/micro_ros_arduino#1158]
- Hardware description: Arduino Nano RP2040 Connect
- RTOS: Mbed OS
- Installation type: Arduino precompiled library
- Version or commit hash: humble

The trigger example mentioned [here](https://micro.ros.org/docs/tutorials/programming_rcl_rclc/executor/#example-2-triggered-execution) works with timer and service but it does not trigger action server handles.

**Comment by pablogs9** [comment]
Please provide details and code for replicating the issue.

**Comment by pablogs9** [comment]
Any update on this?

**Comment by metanav** [comment]
I don't remember the context so closing it.
