### ISSUE TITLE
Question about Support for Arduino Uno

### ISSUE THREAD

**Issue by eleehiga** [micro-ROS/micro_ros_arduino#1166]
Hello, I was wondering, does micro_ros_arduino support the Arduino Uno? Thank you.

**Comment by pablogs9** [comment]
Hello @eleehiga, Arduino UNO has an 8-bit microcontroller with 2 kB of RAM. The common target for micro-ROS is 32-bits microcontrollers with a minimum of approx. 32 kB of RAM. 

We do not support Arduino UNO, and probably using micro-ROS on it would be a really hard task.
Why do you need such support?

I'm closing, but feel free to ask whatever you need.

**Comment by eleehiga** [comment]
@pablogs9 Ah ok I understand, I wanted to ask for such support as I happen to own an Arduino UNO
