### ISSUE TITLE
microros build : could not determine ref type,  find: cannot delete ‘/project/src/’: Directory not empty

### ISSUE THREAD

**Issue by Jenifen** [micro-ROS/micro_ros_arduino#1197]
- Hardware description: Portenta H7 machine control 
- Installation type: Docker
- Version or commit hash: foxy

I'm trying to build the precompiled library, i did the following:
1. git clone -b foxy https://github.com/micro-ROS/micro_ros_arduino
2. sudo docker pull microros/micro_ros_static_library_builder:foxy
3. sudo docker run -it --rm -v $(pwd):/project --env MICROROS_LIBRARY_FOLDER=extras microros/micro_ros_static_library_builder:foxy -p portenta-m7

However, it seems that it cannot overwrite files present and the tracetool fail to clone : 
![image](https://user-images.githubusercontent.com/46198024/199058266-752702c7-73f6-44ef-8ecb-0f3022db7f63.png)

**Comment by pablogs9** [comment]
Can you paste here the whole console output?

**Comment by Jenifen** [comment]
Somehow, the problem was from my network connection!  
Thanks
