### ISSUE TITLE
micro ros comunication problem 

### ISSUE THREAD

**Issue by BenSwisa** [micro-ROS/micro_ros_arduino#1247]
hello,
i am having a comunication problem .
i am running a launch file of 3 micro_ros_agents for 3 usb ports that i have : 2 micro_controllers publishing and 1 subscribing.
- when running the launch file than connecting all the devices at once(via a usb-splitting device) i get the following error for 2 out of the 3 ports : 
 open device error      | device: /dev/ttyACM0, errno: 13. Please re-run with superuser

*even though my user has permission to the usb ports*

- when running the launch file than connecting each device once at a time to my ports i have no problem.

for my project i need to connect all my devices at one time and i have no idea why this is happening.

would appreciate any help , thanks in advance

**Comment by pablogs9** [comment]
Does your setup works if you run `ros2 micro_ros_agent micro_ros_agent serial [your serial device] -v6`?

**Comment by pablogs9** [comment]
Which is the error running the command directly?

**Comment by pablogs9** [comment]
Which is the ouput when you run this command `ros2 micro_ros_agent micro_ros_agent serial [your serial device] -v6` ?

**Comment by pablogs9** [comment]
What about `sudo ros2 micro_ros_agent micro_ros_agent serial [your serial device] -v6`?

**Comment by BenSwisa** [comment]
i am getting the following error

sudo ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyAMC0 
sudo: ros2: command not found

**Comment by pablogs9** [comment]
I guess that you have permission issues with your serial ports. Maybe you can find how to ensure that your user has permission to read and write the serial port.

**Comment by BenSwisa** [comment]
the thing is is i plug the devices one by one i have no user permission issues

**Comment by BenSwisa** [comment]
hey I tried it and it worked , what is the reason it works this way and the other way not?

**Comment by pablogs9** [comment]
Issue with your device's permissions? I really don't know.

Closing as solved.
