### ISSUE TITLE
How to apply custom-message in micro_ros_arduino

### ISSUE THREAD

**Issue by Heaven-KTY** [micro-ROS/micro_ros_arduino#1313]
Issue template
- Hardware description: ESP32
- RTOS: N/A
- Installation type: micro_ros_agent
- Version or commit hash: foxy

Steps to reproduce the issue
I added the generated msg files from ROS2 directly to the src directory of micro_ros_arduino. However, an error occurs during compilation in the Arduino-IDE, 

Expected behavior
Below is Arduino Debug.
"**c:/users/..../appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\micro-ros_publisher.ino.cpp.o:(.literal._Z5setupv+0x28): undefined reference to rosidl_typesupport_c__get_message_type_support_handle__tutorial_interfaces__msg__Num' c:/users/..../appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\micro-ros_publisher.ino.cpp.o: in functionsetup()': C:\Users....\Documents\micro\micro-ros_publisher/micro-ros_publisher.ino:65: undefined reference to `rosidl_typesupport_c__get_message_type_support_handle__tutorial_interfaces__msg__Num' collect2.exe: error: ld returned 1 exit status exit status 1**"

Actual behavior
It doesn't compile.

Additional information.
Where on earth is this problem coming from?
Do I need to go through certain steps in ROS2 before applying the library in 'micro_ros_arduino'?

**Comment by pablogs9** [comment]
You need to rebuild your library:  https://github.com/micro-ROS/micro_ros_arduino#how-to-build-the-precompiled-library
adding your msg packages to `extra_packages` folder.
