### ISSUE TITLE
reconnection example could not run properly over wifi

### ISSUE THREAD

**Issue by marklee56826** [micro-ROS/micro_ros_arduino#1340]
Hi, 
I really appreciate this amazing micro-ROS project and I am learning it. 

My problem: when I tested the reconnection example: micro-ros_reconnection_example, I found that it could not run properly over wifi (serial transport OK).  

Description: Compiling smoothly, but after starting the agent with the command: docker run -it --rm --net=host microros/micro-ros-agent:humble udp4 --port 8888  (already updated), the agent could not be steadily connected. 

Expected behavior:
Solid LED when successfully connected to agent, publishing topics.

Actual behavior:
Flashing LED with nothing published:
......
[1678409815.632855] info     | Root.cpp           | create_client            | create                 | client_key: 0x76432A75, session_id: 0x81
[1678409815.632968] info     | SessionManager.hpp | establish_session        | session established    | client_key: 0x76432A75, address: 192.168.0.10:47138
[1678409815.686132] info     | ProxyClient.cpp    | create_participant       | participant created    | client_key: 0x76432A75, participant_id: 0x000(1)
[1678409815.694138] info     | ProxyClient.cpp    | create_topic             | topic created          | client_key: 0x76432A75, topic_id: 0x000(2), participant_id: 0x000(1)
[1678409815.701274] info     | ProxyClient.cpp    | create_publisher         | publisher created      | client_key: 0x76432A75, publisher_id: 0x000(3), participant_id: 0x000(1)
[1678409815.710856] info     | ProxyClient.cpp    | create_datawriter        | datawriter created     | client_key: 0x76432A75, datawriter_id: 0x000(5), publisher_id: 0x000(3)
[1678409816.447346] info     | Root.cpp           | delete_client            | delete                 | client_key: 0x76432A75
[1678409816.447402] info     | SessionManager.hpp | destroy_session          | session closed         | client_key: 0x76432A75, address: 192.168.0.10:47138
…… beginning to loop

My system: board ESP32-DevKit, agent machine: Intel NUC i5, Ubuntu 22.04, ROS humble, Client and agent have the same domain_id. 

What’s the problem? I did a lot of searches, without finding any solution.
Please help me. Thank you.

**Comment by pablogs9** [comment]
Have you tried to use https://github.com/micro-ROS/micro_ros_espidf_component ?

**Comment by marklee56826** [comment]
Thank you for your kind reply, I will try it.

**Comment by marklee56826** [comment]
Hi, @pablogs9 
I tried and used micro-ROS component for ESP-IDF to run its own example code int32_publisher successfully, but still, I am unable to run micro-ros_reconnection_example on this platform.
1.I used int32_publisher to hold the source file micro-ros_reconnection_example.ino and changed the name to reconnection_example.c and modified the CMakeLists.txt.
2.Put micro_ros_arduino library into the include directory of the micro_ros_espidf_component
3.Build the project with docker container.

The output as follows:
……
[100/101] Generating binary image from built executable
esptool.py v4.4
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Generated /micro_ros_espidf_component/test_reconnection/int32_publisher/build/bootloader/bootloader.bin
[101/101] cd /micro_ros_espidf_component/test_reconnection/int32_publisher/build/bootloader/esp-idf/esptool_py && /opt/esp/python_env/idf5.0_py3.8_env/bin/python /opt/esp/idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /micro_ros_espidf_component/test_reconnection/int32_publisher/build/bootloader/bootloader.bin
Bootloader binary size 0x6710 bytes. 0x8f0 bytes (8%) free.
[840/846] Building C object esp-idf/mai...df_main.dir/microros_reconnection.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/microros_reconnection.c.obj 
ccache /opt/esp/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -I/micro_ros_espidf_component/test_reconnection/int32_publisher/build/config -I/opt/esp/idf/components/newlib/platform_include -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/include -I/opt/esp/idf/components/freertos/esp_additions/include/freertos -I/opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/opt/esp/idf/components/freertos/esp_additions/include -I/opt/esp/idf/components/esp_hw_support/include -I/opt/esp/idf/components/esp_hw_support/include/soc -I/opt/esp/idf/components/esp_hw_support/include/soc/esp32 -I/opt/esp/idf/components/esp_hw_support/port/esp32/. -I/opt/esp/idf/components/esp_hw_support/port/esp32/private_include -I/opt/esp/idf/components/heap/include -I/opt/esp/idf/components/log/include -I/opt/esp/idf/components/soc/include -I/opt/esp/idf/components/soc/esp32/. -I/opt/esp/idf/components/soc/esp32/include -I/opt/esp/idf/components/hal/esp32/include -I/opt/esp/idf/components/hal/include -I/opt/esp/idf/components/hal/platform_port/include -I/opt/esp/idf/components/esp_rom/include -I/opt/esp/idf/components/esp_rom/include/esp32 -I/opt/esp/idf/components/esp_rom/esp32 -I/opt/esp/idf/components/esp_common/include -I/opt/esp/idf/components/esp_system/include -I/opt/esp/idf/components/esp_system/port/soc -I/opt/esp/idf/components/esp_system/port/include/private -I/opt/esp/idf/components/xtensa/include -I/opt/esp/idf/components/xtensa/esp32/include -I/opt/esp/idf/components/lwip/include -I/opt/esp/idf/components/lwip/include/apps -I/opt/esp/idf/components/lwip/include/apps/sntp -I/opt/esp/idf/components/lwip/lwip/src/include -I/opt/esp/idf/components/lwip/port/esp32/include -I/opt/esp/idf/components/lwip/port/esp32/include/arch -I/opt/esp/idf/components/esp_ringbuf/include -I/opt/esp/idf/components/efuse/include -I/opt/esp/idf/components/efuse/esp32/include -I/opt/esp/idf/components/driver/include -I/opt/esp/idf/components/driver/deprecated -I/opt/esp/idf/components/driver/esp32/include -I/opt/esp/idf/components/esp_pm/include -I/opt/esp/idf/components/mbedtls/port/include -I/opt/esp/idf/components/mbedtls/mbedtls/include -I/opt/esp/idf/components/mbedtls/mbedtls/library -I/opt/esp/idf/components/mbedtls/esp_crt_bundle/include -I/opt/esp/idf/components/esp_app_format/include -I/opt/esp/idf/components/bootloader_support/include -I/opt/esp/idf/components/bootloader_support/bootloader_flash/include -I/opt/esp/idf/components/esp_partition/include -I/opt/esp/idf/components/app_update/include -I/opt/esp/idf/components/spi_flash/include -I/opt/esp/idf/components/pthread/include -I/opt/esp/idf/components/esp_timer/include -I/opt/esp/idf/components/app_trace/include -I/opt/esp/idf/components/esp_event/include -I/opt/esp/idf/components/nvs_flash/include -I/opt/esp/idf/components/esp_phy/include -I/opt/esp/idf/components/esp_phy/esp32/include -I/opt/esp/idf/components/vfs/include -I/opt/esp/idf/components/esp_netif/include -I/opt/esp/idf/components/wpa_supplicant/include -I/opt/esp/idf/components/wpa_supplicant/port/include -I/opt/esp/idf/components/wpa_supplicant/esp_supplicant/include -I/opt/esp/idf/components/esp_wifi/include -I/opt/esp/idf/components/unity/include -I/opt/esp/idf/components/unity/unity/src -I/opt/esp/idf/components/cmock/CMock/src -I/opt/esp/idf/components/console -I/opt/esp/idf/components/http_parser -I/opt/esp/idf/components/esp-tls -I/opt/esp/idf/components/esp-tls/esp-tls-crypto -I/opt/esp/idf/components/esp_adc/include -I/opt/esp/idf/components/esp_adc/interface -I/opt/esp/idf/components/esp_adc/esp32/include -I/opt/esp/idf/components/esp_adc/deprecated/include -I/opt/esp/idf/components/esp_eth/include -I/opt/esp/idf/components/esp_gdbstub/include -I/opt/esp/idf/components/esp_gdbstub/xtensa -I/opt/esp/idf/components/esp_gdbstub/esp32 -I/opt/esp/idf/components/esp_hid/include -I/opt/esp/idf/components/tcp_transport/include -I/opt/esp/idf/components/esp_http_client/include -I/opt/esp/idf/components/esp_http_server/include -I/opt/esp/idf/components/esp_https_ota/include -I/opt/esp/idf/components/esp_lcd/include -I/opt/esp/idf/components/esp_lcd/interface -I/opt/esp/idf/components/protobuf-c/protobuf-c -I/opt/esp/idf/components/protocomm/include/common -I/opt/esp/idf/components/protocomm/include/security -I/opt/esp/idf/components/protocomm/include/transports -I/opt/esp/idf/components/esp_local_ctrl/include -I/opt/esp/idf/components/esp_psram/include -I/opt/esp/idf/components/espcoredump/include -I/opt/esp/idf/components/espcoredump/include/port/xtensa -I/opt/esp/idf/components/wear_levelling/include -I/opt/esp/idf/components/sdmmc/include -I/opt/esp/idf/components/fatfs/diskio -I/opt/esp/idf/components/fatfs/vfs -I/opt/esp/idf/components/fatfs/src -I/opt/esp/idf/components/idf_test/include -I/opt/esp/idf/components/idf_test/include/esp32 -I/opt/esp/idf/components/ieee802154/include -I/opt/esp/idf/components/json/cJSON -I/opt/esp/idf/components/mqtt/esp-mqtt/include -I/opt/esp/idf/components/perfmon/include -I/opt/esp/idf/components/spiffs/include -I/opt/esp/idf/components/ulp/ulp_common/include -I/opt/esp/idf/components/ulp/ulp_common/include/esp32 -I/opt/esp/idf/components/wifi_provisioning/include -I/micro_ros_espidf_component/network_interfaces -isystem /micro_ros_espidf_component/include -isystem /micro_ros_espidf_component/include/action_msgs -isystem /micro_ros_espidf_component/include/actionlib_msgs -isystem /micro_ros_espidf_component/include/builtin_interfaces -isystem /micro_ros_espidf_component/include/composition_interfaces -isystem /micro_ros_espidf_component/include/diagnostic_msgs -isystem /micro_ros_espidf_component/include/example_interfaces -isystem /micro_ros_espidf_component/include/geometry_msgs -isystem /micro_ros_espidf_component/include/include -isystem /micro_ros_espidf_component/include/lifecycle_msgs -isystem /micro_ros_espidf_component/include/micro_ros_msgs -isystem /micro_ros_espidf_component/include/micro_ros_utilities -isystem /micro_ros_espidf_component/include/nav_msgs -isystem /micro_ros_espidf_component/include/rcl -isystem /micro_ros_espidf_component/include/rcl_action -isystem /micro_ros_espidf_component/include/rcl_interfaces -isystem /micro_ros_espidf_component/include/rcl_lifecycle -isystem /micro_ros_espidf_component/include/rcl_logging_interface -isystem /micro_ros_espidf_component/include/rclc -isystem /micro_ros_espidf_component/include/rclc_lifecycle -isystem /micro_ros_espidf_component/include/rclc_parameter -isystem /micro_ros_espidf_component/include/rcutils -isystem /micro_ros_espidf_component/include/rmw -isystem /micro_ros_espidf_component/include/rmw_microros -isystem /micro_ros_espidf_component/include/rmw_microxrcedds_c -isystem /micro_ros_espidf_component/include/rosgraph_msgs -isystem /micro_ros_espidf_component/include/rosidl_runtime_c -isystem /micro_ros_espidf_component/include/rosidl_typesupport_c -isystem /micro_ros_espidf_component/include/rosidl_typesupport_interface -isystem /micro_ros_espidf_component/include/rosidl_typesupport_introspection_c -isystem /micro_ros_espidf_component/include/rosidl_typesupport_microxrcedds_c -isystem /micro_ros_espidf_component/include/sensor_msgs -isystem /micro_ros_espidf_component/include/shape_msgs -isystem /micro_ros_espidf_component/include/src -isystem /micro_ros_espidf_component/include/statistics_msgs -isystem /micro_ros_espidf_component/include/std_msgs -isystem /micro_ros_espidf_component/include/std_srvs -isystem /micro_ros_espidf_component/include/stereo_msgs -isystem /micro_ros_espidf_component/include/test_msgs -isystem /micro_ros_espidf_component/include/tracetools -isystem /micro_ros_espidf_component/include/trajectory_msgs -isystem /micro_ros_espidf_component/include/ucdr -isystem /micro_ros_espidf_component/include/unique_identifier_msgs -isystem /micro_ros_espidf_component/include/uxr -isystem /micro_ros_espidf_component/include/visualization_msgs -mlongcalls -Wno-frame-address  -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/micro_ros_espidf_component/test_reconnection/int32_publisher=. -fmacro-prefix-map=/opt/esp/idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"HEAD-HASH-NOTFOUND\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/microros_reconnection.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/microros_reconnection.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/microros_reconnection.c.obj -c /micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c
In file included from /micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:1:
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:27:8: error: expected identifier or '(' before string constant
   27 | extern "C" bool arduino_transport_open(struct uxrCustomTransport * transport);
      |        ^~~
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:28:8: error: expected identifier or '(' before string constant
   28 | extern "C" bool arduino_transport_close(struct uxrCustomTransport * transport);
      |        ^~~
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:29:8: error: expected identifier or '(' before string constant
   29 | extern "C" size_t arduino_transport_write(struct uxrCustomTransport* transport, const uint8_t * buf, size_t len, uint8_t * err);
      |        ^~~
In file included from /micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:1:
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:30:8: error: expected identifier or '(' before string constant
   30 | extern "C" size_t arduino_transport_read(struct uxrCustomTransport* transport, uint8_t* buf, size_t len, int timeout, uint8_t* err);
      |        ^~~
/micro_ros_espidf_component/include/src/micro_ros_arduino.h: In function 'set_microros_transports':
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:36:17: error: 'arduino_transport_open' undeclared (first use in this function)
   36 |                 arduino_transport_open,
      |                 ^~~~~~~~~~~~~~~~~~~~~~
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:36:17: note: each undeclared identifier is reported only once for each function it appears in
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:37:17: error: 'arduino_transport_close' undeclared (first use in this function)
   37 |                 arduino_transport_close,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:38:17: error: 'arduino_transport_write' undeclared (first use in this function)
   38 |                 arduino_transport_write,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
/micro_ros_espidf_component/include/src/micro_ros_arduino.h:39:17: error: 'arduino_transport_read' undeclared (first use in this function)
   39 |                 arduino_transport_read
      |                 ^~~~~~~~~~~~~~~~~~~~~~
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c: In function 'setup':
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:97:3: error: implicit declaration of function 'pinMode' [-Werror=implicit-function-declaration]
   97 |   pinMode(LED_PIN, OUTPUT);
      |   ^~~~~~~
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:97:20: error: 'OUTPUT' undeclared (first use in this function)
   97 |   pinMode(LED_PIN, OUTPUT);
      |                    ^~~~~~
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c: In function 'loop':
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:130:5: error: implicit declaration of function 'digitalWrite' [-Werror=implicit-function-declaration]
  130 |     digitalWrite(LED_PIN, 1);
      |     ^~~~~~~~~~~~
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c: In function 'timer_callback':
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:40:5: warning: ignoring return value of 'rcl_publish' declared with attribute 'warn_unused_result' [-Wunused-result]
   40 |     rcl_publish(&publisher, &msg, NULL);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c: In function 'destroy_entities':
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:88:3: warning: ignoring return value of 'rcl_publisher_fini' declared with attribute 'warn_unused_result' [-Wunused-result]
   88 |   rcl_publisher_fini(&publisher, &node);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:89:3: warning: ignoring return value of 'rcl_timer_fini' declared with attribute 'warn_unused_result' [-Wunused-result]
   89 |   rcl_timer_fini(&timer);
      |   ^~~~~~~~~~~~~~~~~~~~~~
/micro_ros_espidf_component/test_reconnection/int32_publisher/main/microros_reconnection.c:91:3: warning: ignoring return value of 'rcl_node_fini' declared with attribute 'warn_unused_result' [-Wunused-result]
   91 |   rcl_node_fini(&node);
      |   ^~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

4. I also tried to modify the code to remove the errors, for example:
   if changing from .c to cpp, still has "error: 'arduino_transport_open' undeclared (first use in this function)..."
   if removing the fuction:set_microros_transports, causes "error: undefined reference to `app_main' "
   ......

Please help me to find the problem or tell me how to use arduino IDE to run micro-ros_reconnection_example with wifi transport. Thank you very much.

**Comment by pablogs9** [comment]
> 2.Put micro_ros_arduino library into the include directory of the micro_ros_espidf_component

Why?

**Comment by marklee56826** [comment]
Hi, thank you for kind reply. 
Because if not, I got the error: Not found micro_ros_arduino.h, not such file or directiory. Then the compiling stops. I am sorry I don't know how to remove the error.

**Comment by marklee56826** [comment]
Hi, @pablogs9
 I tried to modify the file micro-ros_reconnection_example.ino and got the following result, which seems much better now:
……
/opt/esp/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/11.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/freertos/libfreertos.a(port_common.c.obj):(.literal.main_task+0x8): undefined reference to `app_main'
/opt/esp/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/11.2.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/freertos/libfreertos.a(port_common.c.obj): in function `main_task':
/opt/esp/idf/components/freertos/FreeRTOS-Kernel/portable/port_common.c:100: undefined reference to `app_main'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
……
What should I do to get rid of the error?

**Comment by marklee56826** [comment]
The errors in the esp-idf code were finally eliminated but the result seems not as expected. I don't know where is the problem.

**Comment by pablogs9** [comment]
So please, provide details (preferably in the correct repo issues) about which are the not expected results.

**Comment by marklee56826** [comment]
Hi,  @pablogs9 
I am sorry I did not make myself understood. 
“Not as expected” means the result of my trying to run reconnection_example over WiFi network. I tried in different dev environment such as Arduino IDE, Plamformio, ESP-IDF. Unfortunately, the micro-ROS client cannot connect to the Agent properly. No issue with serial transport as the example in the repo.
My experiments showed that the reconnection_example with wifi transport could be compiled smoothly, but when running on ubuntu 22.04, esp32 board will always in a dead loop: connect and then disconnect.
 The connection to wifi network is good, and the only problem exists in the connection to Agent. 
I am sorry I am a beginner and my question may be too basic: would you like to tell me whether the reconnection_example can run on wifi network, not just on serial port?
Micro-ROS is really a great project and I like it very much and will continue to learn it.
Thank you for your patience and kindness.
