### ISSUE TITLE
roadmap Infineon support TC39x ?

### ISSUE THREAD

**Issue by fengtuo58** [micro-ROS/micro_ros_arduino#1375]
## Issue template

- Hardware description: 
- RTOS: 
- Installation type: 
- Version or commit hash: 
**support Infineon TC397x ?**
#### Expected behavior
support 
#### Actual behavior
not support
#### Additional information
Are there  roadmap to support it ?

**Comment by pablogs9** [comment]
Hello @fengtuo58,

There is no plan for supporting this device in our roadmap.

If you need professional services please feel free to contact support@eProsima.com

**Comment by fengtuo58** [comment]
thanks
