### ISSUE TITLE
Support for embeddedRTPS in micro_ros_arduino

### ISSUE THREAD

**Issue by kalaajiahmad** [micro-ROS/micro_ros_arduino#1376]
Hey,

I am curious if embeddedrtps can be enabled somehow using this mico_ros_arduino library?
I am interested in running our ESP32 powered Robots without the need for an Agent on the Host PC if possible.
I read about the support of eprosima for embeddedRTPS and want to see how i can enable it and test it.
My feeling was that the colcon.meta file would have a middleware param, but that doesn;t seem like the case.
If still not supported i would be more then happy to work on such a feature and provide a PR for it and enable it in this repository.

Whoever is responsible, let me know your thoughts :)

**Comment by pablogs9** [comment]
Hello @kalaajiahmad, we are not planning to support embeddedRTPS in micro-ROS for Arduino libraries.

If you need professional support, we provide other (non-OSS) middlewares that are agent-less and can be integrated into this kind of platform. If you need professional support please contact support@eProsima.com
