### ISSUE TITLE
Publisher delayed while using Adafruit NeoPixel strip 

### ISSUE THREAD

**Issue by Tyce11** [micro-ROS/micro_ros_arduino#1468]
- Version or commit hash: Humble

#### Steps to reproduce the issue

- Create a publisher
- Implement Adafruit NeoPixel functionality
- Have both the publisher and the NeoPixel both running 

#### Expected behavior

- Publisher will publish it's message at the desired frequency

#### Actual behavior

- Publisher publishes its message at a random frequency

#### Additional information
I'm using the NeoPixel strip to light up according to what percentage the battery I am using is on. I also have battery info as well as other sensor info publishing to their respective topics. When NeoPixel functionality is removed from the sketch all publishers publish at the desired frequency. When NeoPixel functionality is implemented the publishers no longer publish at the frequency that is specified in the program, but will instead publish the messages at a random rate. I have tried to implement the NeoPixel in both the loop function and in the publisher call back. Any ideas on what causes this delay to happen?

**Comment by Acuadros95** [comment]
> Any ideas on what causes this delay to happen?

Most probably a delay on the NeoPixel communications. Also its not a good idea to include a method with delay on a micro-ROS timer callback.

I am closing as this is not micro-ROS related, but if you can provide more data abour your problem, we will be happy to help.
