### ISSUE TITLE
Build fails on Windows when using git clone

### ISSUE THREAD

**Issue by kaiaai** [micro-ROS/micro_ros_arduino#1489]
## Issue template
- Hardware description:
The development machine is a Windows PC laptop

- RTOS:
ESP32 Arduino (FreeRTOS)

- Installation type:
Build micro_ros_arduino library using a Docker image
Docker for Windows, Arduino 1.8.13, hub.docker.com image microros/micro_ros_static_library_builder:iron

- Version or commit hash:
Iron

#### Steps to reproduce the issue
In a Windows PowerShell
```
cmd.exe
cd %HOMEPATH%\Documents\Arduino\libraries
git clone -b iron --depth 1 https://github.com/micro-ROS/micro_ros_arduino
docker run -it --rm -v .\micro_ros_arduino:/project --env MICROROS_LIBRARY_FOLDER=extras microros/micro_ros_static_library_builder:iron -p esp32
```
#### Expected behavior
Build to succeed

#### Actual behavior
The build fails to start with these errors
```
/entrypoint.sh: /project/extras/library_generation/library_generation.sh: /bin/bash^M: bad interpreter: No such file or directory
/entrypoint.sh: line 9: /project/extras/library_generation/library_generation.sh: Success
```

#### Additional information
This is because library_generation.sh (located on Windows at ~\Documents\Arduino\libraries\micro_ros_arduino\extras\library_generation\library_generation.sh) gets git-cloned using CRLF line endings. Unlike git-cloning the repo, downloading the library as a .ZIP release and building works fine because the zipped files have correct LF endings.

To fix this, how about creating a .gitattributes at the repo root with this contents (or I can create a PR for you)
```
*.sh text eol=lf
*.meta text eol=lf
*.cmake text eol=lf
*.repos text eol=lf
```
Also, maybe it would be good to update the library build instructions (include the git clone command) for those who git-clone the repo instead of downloading the .ZIP release.

**Comment by pablogs9** [comment]
The library generation tool does not support Windows, please use it under Linux
