### ISSUE TITLE
Stale Docker image(s), broken, tagged latest

### ISSUE THREAD

**Issue by iovsiann** [micro-ROS/micro_ros_arduino#1495]
## Issue template
I cannot help noticing two images Docker Hub being stale/abandoned yet tagged latest.

microros/micro_ros_static_library_builder:latest Digest fa3713db495c Last pushed 2 years ago by microros
microros/micro-ros-agent:latest Digest b849a2bb0306 Last pushed 2 years ago by microros

#### Steps to reproduce the issue
Pull the 2nd image, use it to build a library.

#### Expected behavior
Library build fails.

#### Actual behavior
The first one is broken, i.e. it fails a library build.

#### Additional information
Would you consider removing or fixing those images? Thank you.

**Comment by pablogs9** [comment]
Done, thanks for notifying.
