### ISSUE TITLE
Session Not Established

### ISSUE THREAD

**Issue by bobkim938** [micro-ROS/micro_ros_arduino#1574]
## Issue template

- Hardware description: Arduino Nano rp2040 connect
- RTOS: N/A
- Installation type: Android IDE 2.2.1
- Version or commit hash: v2.0.7 Humble

I'm very new to ROS, so it would be very appreciated if I can figure out the issue.
I wanted to test using the publish example code if I can publish from arduino to my PC. 
Indeed, if I use micro-ros_reconnection_example, it works, I'm not sure why.
I followed the official installation procedures, and I did not make any changes to ROS_DOMAIN_ID.
`ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM0 -v6`
The session was not established using the above command.

#### Expected behavior
I expected the session to be established
#### Actual behavior
The only log I got was as the below image.
![image](https://github.com/micro-ROS/micro_ros_arduino/assets/115132363/75aeb7bc-278f-460f-9755-8f4b179c69ea)

**Comment by pablogs9** [comment]
Are you resetting the board after instantiating the micro-ROS Agent?

This example do not handle client-agent reconnection, see this for implementing it: https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/handle_reconnections/handle_reconnections.html

**Comment by bobkim938** [comment]
Should I reset the board, after instantiating?

**Comment by pablogs9** [comment]
Please read: https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/handle_reconnections/handle_reconnections.html

**Comment by bobkim938** [comment]
Thank you so much, I was able to somehow solve the issue.
