### ISSUE TITLE
Serial monitor on arduino showing partial gibberish

### ISSUE THREAD

**Issue by TheHassanShahzad** [micro-ROS/micro_ros_arduino#1621]
## Issue template

- Hardware description: 
host os: ubuntu 22.04.2 
running ros2 humble

#### Steps to reproduce the issue
running a slightly modified version of example twist subscriber on the xiao :
`#include <micro_ros_arduino.h>
#include <stdio.h>
#include <rcl/rcl.h>
#include <rcl/error_handling.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include <geometry_msgs/msg/twist.h>

rcl_subscription_t subscriber;
geometry_msgs__msg__Twist msg;
rclc_executor_t executor;
rcl_allocator_t allocator;
rclc_support_t support;
rcl_node_t node;

#define LED_PIN 13

#define RCCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){error_loop();}}
#define RCSOFTCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){error_loop();}}

void error_loop(){
  while(1){
    digitalWrite(LED_PIN, !digitalRead(LED_PIN));
    delay(100);
    Serial.println("Error occurred. Toggling LED.");
  }
}

// twist message cb
void subscription_callback(const void *msgin) {
  const geometry_msgs__msg__Twist * msg = (const geometry_msgs__msg__Twist *)msgin;
  
  // Output received Twist message
  Serial.print("Received Twist message:\n");
  Serial.print("Linear: x = ");
  Serial.print(msg->linear.x);
  Serial.print(", y = ");
  Serial.print(msg->linear.y);
  Serial.print(", z = ");
  Serial.println(msg->linear.z);
  
  Serial.print("Angular: x = ");
  Serial.print(msg->angular.x);
  Serial.print(", y = ");
  Serial.print(msg->angular.y);
  Serial.print(", z = ");
  Serial.println(msg->angular.z);

  // if velocity in x direction is 0 turn off LED, if 1 turn on LED
  digitalWrite(LED_PIN, (msg->linear.x == 0) ? LOW : HIGH);
  Serial.println("LED state updated.");
}

void setup() {
  Serial.begin(9600); // Initialize serial communication
  set_microros_transports();
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, HIGH);  
  
  delay(2000);

  allocator = rcl_get_default_allocator();

  // create init_options
  RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));

  // create node
  RCCHECK(rclc_node_init_default(&node, "micro_ros_arduino_node", "", &support));
  Serial.println("Node initialized.");

  // create subscriber
  RCCHECK(rclc_subscription_init_default(
    &subscriber,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Twist),
    "cmd_vel"));
  Serial.println("Subscriber initialized.");

  // create executor
  RCCHECK(rclc_executor_init(&executor, &support.context, 1, &allocator));
  RCCHECK(rclc_executor_add_subscription(&executor, &subscriber, &msg, &subscription_callback, ON_NEW_DATA));
  Serial.println("Executor initialized.");
}

void loop() {
  delay(100);
  RCCHECK(rclc_executor_spin_some(&executor, RCL_MS_TO_NS(100)));
}
`

#### Expected behavior
serial monitor only prints the recieved twist messages on the 960 baud rate
#### Actual behavior
it prints the twist messages along with gibberrish which i assume is the serial communication between the laptop and xiao also being displayed in serial monitor

![image](https://github.com/micro-ROS/micro_ros_arduino/assets/94758916/0af3cb38-d68e-4a74-b10d-502c5d5dc285)

**Comment by pablogs9** [comment]
As far as micro-ROS client is communication with the micro-ROS Agent via serial port, you **cannot** use the very same serial port for printing data.
