### ISSUE TITLE
Micro_ros_arduino on esp32

### ISSUE THREAD

**Issue by Joelmaca9** [micro-ROS/micro_ros_arduino#164]
Hello guys! I'm currently working on a project using an ESP32 board with arduino as component. I would like to use this library to implement ROS2 in my project but I'm having some troubles, and I don kow if it is posible to do what I want. Has anybody tried before to include this library as component and make it work? 

Thanks in advance!

**Comment by pablogs9** [comment]
Hello @Joelmaca9, if you want to add micro-ROS to ESP32 IDF as a component better use this other repo: https://github.com/micro-ROS/micro_ros_espidf_component

**Comment by pablogs9** [comment]
In my opinion, if you are going to work with ESP32 you should be using the IDF component, why don't you open an issue there, close this one and we can discuss in the other how to build your application using IDF and micro-ROS as a component?

**Comment by Joelmaca9** [comment]
All right! Thank you very much
