### ISSUE TITLE
Unable to compile Arduino code, undefined reference

### ISSUE THREAD

**Issue by aistehoo** [micro-ROS/micro_ros_arduino#1760]
![Screenshot from 2024-05-17 10-29-09](https://github.com/micro-ROS/micro_ros_arduino/assets/170063330/6df76651-f032-43e6-9d64-db1615a3f686)

Software: ROS2 Humble, Arduino 1.8.19, Micro ROS Humble v2.0.5

Hardware: Arduino Due

I am unable to build the code. I've considered patching the platform.txt into .../hardware/sam/1.6.12 and building the meta file. All the header files are in. Could it be missing access to the c files? Or, what steps did I miss?

However, you may ignore the other errors from my custom functions. That is resolved on my end.

**Comment by aistehoo** [comment]
I only added in the .ZIP file into Arduino library along with the platform.txt 

Am I missing out on anything else?

You may ignore the other errors by my custom functions.

**Comment by aistehoo** [comment]
I've resolved my issue. Apparently, the humble version requires a different type of txt patching! Please check the correct branch on Git.

Realise the difference between default iron version and humble version:

Iron:
curl https://raw.githubusercontent.com/micro-ROS/micro_ros_arduino/iron/extras/patching_boards/platform_arduinocore_sam.txt > platform.txt

Humble:
curl https://raw.githubusercontent.com/micro-ROS/micro_ros_arduino/main/extras/patching_boards/platform_arduinocore_sam.txt > platform.txt

**Comment by saitama-00** [comment]
can you elaborate please
