### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by amfern** [micro-ROS/micro_ros_arduino#177]
## Issue template

- Hardware description: teensy3.2, stm32f7
- RTOS:
- Installation type: running library_generation.sh script
- Version or commit hash: foxy

#### Steps to reproduce the issue
when building the library with library_generation.sh it will download the latest packages and build the static `libmicroros.a` libraries, but is there a way to lock the package versions to have a reproducible builds?

**Comment by pablogs9** [comment]
Not by automatically... You will need to use the builder manually and checkout the required commits.
