### ISSUE TITLE
Support for Arduino Uno R4 Wifi

### ISSUE THREAD

**Issue by Amronos** [micro-ROS/micro_ros_arduino#1830]
Can support for [Arduino Uno R4 Wifi](https://docs.arduino.cc/hardware/uno-r4-wifi/) be added? It features an ESP32-S3 which can be separately programmed via a specific header.

**Comment by hippo5329** [comment]
Why do you want to use Uno R4? What robot do you want to build?

If you are new to micro-ROS, you should get started with esp32 or pico. Follow the wiki

https://github.com/hippo5329/micro_ros_arduino_examples_platformio/wiki

https://github.com/hippo5329/linorobot2_hardware/wiki
