### ISSUE TITLE
Jazzy precompiled library release

### ISSUE THREAD

**Issue by EnzoGhisoni** [micro-ROS/micro_ros_arduino#1851]
Is it planned  to add the precompiled library for Jazzy to the release list?
Does the Jazzy version require additional development?

**Comment by hippo5329** [comment]
The current default branch is Jazzy already. Please check the README.

**Comment by hippo5329** [comment]
You might want to switch to platformio and vscode. They are more powerful and do not need the precompiled library.

https://github.com/hippo5329/micro_ros_arduino_examples_platformio/wiki

**Comment by pablogs9** [comment]
Jazzy is the default branch: https://github.com/micro-ROS/micro_ros_arduino/tree/jazzy
