### ISSUE TITLE
Why does microros arduino not work for esp32 s3 room?

### ISSUE THREAD

**Issue by SamsonAjadalu** [micro-ROS/micro_ros_arduino#1873]

**Comment by hippo5329** [comment]
micro-ros arduino does not supports esp32-s3 yet. You may switch to platformio.

    pio run -e esp32s3 -t upload

https://github.com/hippo5329/micro_ros_arduino_examples_platformio/wiki

**Comment by SamsonAjadalu** [comment]
This works but just wanted to use arduino ide. Thanks.

**Comment by hippo5329** [comment]
You may switch to vscode with platformio ext, which is more powerful than arduino ide.
