### ISSUE TITLE
build the precompiled library without docker

### ISSUE THREAD

**Issue by UncleMask** [micro-ROS/micro_ros_arduino#196]
hey there! is there a way to build the precompiled library without docker?

**Comment by pablogs9** [comment]
For sure, using the `generate_lib` option of the [micro-ROS Build System](https://github.com/micro-ROS/micro_ros_setup). You can read more [here](https://micro.ros.org/docs/tutorials/advanced/create_custom_static_library/).

**Comment by huak95** [comment]
@UncleMask Can you using the precompiled library without docker?
