### ISSUE TITLE
Add support for Arduino Portenta

### ISSUE THREAD

**Issue by mbanzi** [micro-ROS/micro_ros_arduino#26]
Hi this is great, how about supporting an actual Arduino board 😉  The new Portenta is super powerful (Dual core Cortex M7+M4, wifi,ble and a bunch of other stuff on a small board) and would be a great addition to this project. Would you consider supporting it if we send you some hardware? Let me know :)

**Comment by pablogs9** [comment]
Hello @mbanzi, this new Portenta looks super cool. Of course, we will support it and it would be awesome if you send us some boards. Please reach me at pablogarrido@eprosima.com and I can give you our address.

Thanks for the interest and for sure I will come back soon with the news!

**Comment by pablogs9** [comment]
Friendly reminder @mbanzi. We are suuuuuuper excited about these new boards.

**Comment by mbanzi** [comment]
Sorry for the delay I'll follow up today :)

**Comment by pablogs9** [comment]
We just have received it! Let's try the micro-ROS ports. Thanks a lot, @mbanzi and Arduino team!

![photo5827707147188810919](https://user-images.githubusercontent.com/7647884/106884309-6b5f1400-66e1-11eb-9d3d-6d23354fc55b.jpg)

**Comment by ralph-lange** [comment]
Does it come with a built-in LoRa module? The box says "LoRa Connectivity", but I could not find it in the spec.

**Comment by pablogs9** [comment]
Yes @ralph-lange, it seems that the LoRa module is in the shield: https://store.arduino.cc/portenta-vision-shield

**Comment by pablogs9** [comment]
Closing due to https://github.com/micro-ROS/micro_ros_arduino/pull/65
