### ISSUE TITLE
micro_ros_arduino for ESP32

### ISSUE THREAD

**Issue by ealkhatib** [micro-ROS/micro_ros_arduino#297]
Hi Guys,

How can I used the micro_ros_arduino library on ESP32? 

- Hardware description:  ESP32
- RTOS:  FreeRTOS
- Installation type:  Arduino IDE
- Version or commit hash:  foxy

**Comment by pablogs9** [comment]
By now the best way of using micro-ROS in the ESP32 is using the [micro-ROS IDF component](https://github.com/micro-ROS/micro_ros_espidf_component).
