### ISSUE TITLE
Arduino/Genuino Mega or Mega 2560 Support

### ISSUE THREAD

**Issue by melshaer** [micro-ROS/micro_ros_arduino#321]
Is there a way I can compile the micro-ros library to work on the Arduino Mega 2560? I am aware that it's not supported at the moment but if there are steps I could use to get it work, I would appreciate any guidance.

**Comment by pablogs9** [comment]
Hello, @melshaer micro-ROS is not intended to work in 8-bit MCUs but in 32-bits MCUs. So I see difficult a port for the board you mention.

One option could be to use a [Micro XRCE-DDS](https://github.com/eProsima/Micro-XRCE-DDS-Client) bare application with some restrictions if your requirements force the Mega 2560. If not, I recommend upgrading to a newer board with support for micro-ROS.

I'm closing, do no hesitate to reopen if you have more questions.
