### ISSUE TITLE
Geometry_msg didn't work, for controlling motor speed.

### ISSUE THREAD

**Issue by huak95** [micro-ROS/micro_ros_arduino#428]
Hardware description: Arduino Due
RTOS: NO
Installation type: using static library (Pre-compile)
Version or commit hash: foxy

#### Steps to reproduce the issue
In ROS1 I use this command to create velCallback command to get speed from ROS
`void velCallback( const geometry_msgs::Twist& CVel){    
`
In ROS2 micro_ros_package I tried to use like I use in ROS1 but it's failed so I modified the code like this
```
void velCallback(const geometry_msgs__msg__Twist& CVel){    
    double vel_x = CVel.linear.x;
    double vel_th = CVel.angular.z;
    double right_vel = 0.0;
    double left_vel = 0.0;

    // turning
    if(vel_x == 0){  
        right_vel = vel_th * WheelSeparation / 2.0;
        left_vel = (-1) * right_vel;
    }
    // forward / backward
    else if(vel_th == 0){ 
        left_vel = right_vel = vel_x;
    }
    // moving doing arcs
    else{ 
        left_vel = vel_x - vel_th * WheelSeparation / 2.0;
        right_vel = vel_x + vel_th * WheelSeparation / 2.0;       
    }
    //write new command speeds to global vars 
    WCS[0] = left_vel;
    WCS[1] = right_vel;
}
```
When I use command `sudo docker run -ti --rm --net=host ros:foxy ros2 topic list` It's shown cmd_vel topic, but when I use 
```
sudo docker run -ti --rm --net=host ros:foxy ros2 topic pub --once /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 2.0}}"

publisher: beginning loop
publishing #1: geometry_msgs.msg.Twist(linear=geometry_msgs.msg.Vector3(x=2.0, y=0.0, z=0.0), angular=geometry_msgs.msg.Vector3(x=0.0, y=0.0, z=0.0))
```

The motor won't work, I think the velCallback function don't working.
May I code wrong to get the odom.geometry velocity. 

Thank.

#### Expected behavior

The velCallback can make the motor drive.

#### Actual behavior

The velCallback can't make the motor drive.

**Comment by pablogs9** [comment]
[Here](https://github.com/micro-ROS/micro_ros_arduino/blob/628ad3d15ec1476b4c87c406a7d8b64f7e7544f7/examples/micro-ros_subscriber/micro-ros_subscriber.ino#L32) you have an example of a subscription application in micro-ROS.

Please reopen if you any other problem.
