### ISSUE TITLE
Arduino gets stuck when running node for second time in a row without hard reset

### ISSUE THREAD

**Issue by laronll** [micro-ROS/micro_ros_arduino#445]
I am running Ubuntu 20.04, ROS foxy on a Jetson nano. The Arduino RP 2040 is connected though USB to Jetson and it has a  sensor connected to it by I2C. The node gets data from the sensor to the RP2040 to the Jetson. I have install microros from your Git repo and it is foxy 1.0.

I have successfully ran the node and echo the topic but if I run the ros2 run command a second time after stopping the first time run but it gets stuck saying: 

...~/microros_ws$ ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM3

[1630196560.686372] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1630196560.687177] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4

Thus my problem is that after it runs one time using 'ros2 run' it cannot run again using 'ros2 run'  without hard resetting the RP2040 board.

I would expect that it would  run  anytime I would like to without having to hard reset or disconnecting and reconnecting the board every time to make it work again. 

Thank you in advance.

**Comment by pablogs9** [comment]
By default, the micro-ROS client is not going to reconnect to the micro-ROS Agent. Check [this](https://github.com/micro-ROS/micro_ros_arduino/tree/galactic/examples/micro-ros_reconnection_example) or [this](https://github.com/micro-ROS/micro_ros_arduino/issues/400#issuecomment-903754040)
