### ISSUE TITLE
micro ros with AKX00032 (Arduino Portenta Machine Control - AKX00032)

### ISSUE THREAD

**Issue by SeungRyeol** [micro-ROS/micro_ros_arduino#475]
Hello,

Can I use micro-ros with the board on the link below?
[https://store-usa.arduino.cc/collections/new-products/products/arduino-portenta-machine-control?selectedStore=us](url)

**Comment by pablogs9** [comment]
For sure, the micro-ROS port for Arduino Portenta should work since they use the same MCU.
