### ISSUE TITLE
Microros output

### ISSUE THREAD

**Issue by laronll** [micro-ROS/micro_ros_arduino#496]
How do I change microros output for Arduino? For example it normally prints "data: <integer>" I would like to print "Temperature: <integer> Celsius."

**Comment by pablogs9** [comment]
Where does it prints "data"?

**Comment by laronll** [comment]
The "data" is printed out after I run the node in ros2 and in another terminal run: ros2 topic echo <sensor topic>. Gives me 
data= 21
. 
.
data= 23
And so on.
I would like to print
Temperature: 23 C
And so on.
Thank you

**Comment by pablogs9** [comment]
Not related to micro-ROS, this is the ROS 2 CLI.

**Comment by laronll** [comment]
Thank you. However could I write a message after data that says Temperature in Celsius: <data output>
.
.
And so on?
