### ISSUE TITLE
Support nRF52

### ISSUE THREAD

**Issue by kallaspriit** [micro-ROS/micro_ros_arduino#509]
Would it be possible to run this library on Adafruit Feather nRF52840 Sense?
https://learn.adafruit.com/adafruit-feather-sense?view=all

It's a capable Arduino compatible board based on nRF52 (nRF52840 to be more precise). Could not find a tutorial on how to build the library for other than the supported pre-compiled boards. It's got bluetooth and a bunch of sensors on-board that I would like to use for my robotics project.

Managed to get https://github.com/ROBOTIS-GIT/ros2arduino working on it but for some reason (version mismatches?) the micro ros agent does not communicate with it properly (it opens it but no topic is published).

**Comment by pablogs9** [comment]
Any update on this?
