### ISSUE TITLE
Can't build the precompiled library

### ISSUE THREAD

**Issue by xptosoft** [micro-ROS/micro_ros_arduino#647]
I must be missing something:
```
cd ~/Arduino/libraries/
git clone https://github.com/micro-ROS/micro_ros_arduino.git
cd micro_ros_arduino
docker run -it --rm -v $(pwd):/project --env MICROROS_LIBRARY_FOLDER=extras microros/micro_ros_static_library_builder:galactic
```
Error:
![image](https://user-images.githubusercontent.com/57957556/146627490-d3f335a0-f9a5-450e-928e-3f9594c2dc62.png)

Not a single firmware compiles. 

Please advise.

**Comment by pablogs9** [comment]
Sorry, this has been a bug included in an update of one of the micro-ROS layers. It is solved here: https://github.com/micro-ROS/rmw_microxrcedds/pull/221.

Please retry.
