### ISSUE TITLE
device port disabing in micro-ros

### ISSUE THREAD

**Issue by ajaykumar666** [micro-ROS/micro_ros_arduino#658]
## Issue template

- Hardware description: stm32f4411ce blackpill
- RTOS: micro-ros on ubuntu 20 system
- Installation type: micro_ros_setup
- Version or commit hash: micro-ROS used: foxy

#### Steps to reproduce the issue
Downloaded the Arduino library from the micro_ros repository :
https://github.com/micro-ROS/micro_ros_arduino
and installed the library in Arduino ide.
From the example of micro_ros_arduino in Arduino complied and flashed the micro-ros_publisher into the Blackpill stm32f411ce. Installed micro-ros agent on ubuntu 20.
When blackpill is connected to the system the device port stays active for 10s after that eh port gets deactivated and is not found by the micro-ros agent on ubuntu
![Screenshot from 2021-12-22 17-59-53](https://user-images.githubusercontent.com/30932095/147093117-43e01fab-5f13-41b9-ad02-bd41b586d3fe.png)
so when I reset the blackpill I get this error even when I restart the micro-ros agent
![Screenshot from 2021-12-22 18-03-32](https://user-images.githubusercontent.com/30932095/147093567-5dbf2667-6df2-4c59-89ec-e3cbdc06f442.png)
so now I have to start the blackpill and micro-ros agent all together/simultaneously then it gets connected and publishes the topic in ros2
![Screenshot from 2021-12-22 18-08-18](https://user-images.githubusercontent.com/30932095/147094058-a522b20a-b646-40db-b3c2-cc2e9513400b.png)
 I don't want the hardware to deactivate the port if it doesn't find the micro-ros agent or if the wait time can be customized.
Hope I'm clear this time.

**Comment by pablogs9** [comment]
You can handle the agent status from the client side, please check the client reconnection example: https://github.com/micro-ROS/micro_ros_arduino/blob/galactic/examples/micro-ros_reconnection_example/micro-ros_reconnection_example.ino

**Comment by ajaykumar666** [comment]
thanks a lot, the example solved the error but had to change the reconnection interval parameter to 500 or above to make port available.
