### ISSUE TITLE
Using PlatformIO with Arduino Due

### ISSUE THREAD

**Issue by pnn16004** [micro-ROS/micro_ros_arduino#698]
## Issue template

- Hardware description: Arduino Due
- RTOS: Bare-metal
- Installation type: micro_ros_arduino, PlatformIO, VSCode
- Version or commit hash: Galactic

#### Steps to reproduce the issue
Open an empty Arduino Due (Programming Port) project in PlatformIO.
Copy paste in the 'micro-ros_publisher' example.
Use the following in platformio.ini:
```
[env:due]
platform = atmelsam
board = due
framework = arduino

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino

build_flags =
    -L ./.pio/libdeps/arduino_due/micro_ros_arduino/src/cortex-m3/
    -l microros
    -D SERIAL_UART_INSTANCE=1
```
Build the project.

#### Expected behavior
Successfully build. 

#### Actual behavior
```
Archiving .pio/build/due/libFrameworkArduino.a
Indexing .pio/build/due/libFrameworkArduino.a
Linking .pio/build/due/firmware.elf
.pio/libdeps/due/micro_ros_arduino/src/cortex-m3/libmicroros.a(librmw-validate_full_topic_name.c.obj): In function `rmw_validate_full_topic_name':
validate_full_topic_name.c:(.text.rmw_validate_full_topic_name+0xf8): undefined reference to `__ctype_ptr__'
.pio/libdeps/due/micro_ros_arduino/src/cortex-m3/libmicroros.a(librmw-validate_node_name.c.obj): In function `rmw_validate_node_name':
validate_node_name.c:(.text.rmw_validate_node_name+0x88): undefined reference to `__ctype_ptr__'
.pio/libdeps/due/micro_ros_arduino/src/cortex-m3/libmicroros.a(librcl-validate_topic_name.c.obj): In function `rcl_validate_topic_name':
validate_topic_name.c:(.text.rcl_validate_topic_name+0x1cc): undefined reference to `__ctype_ptr__'
collect2: error: ld returned 1 exit status
*** [.pio/build/due/firmware.elf] Error 1
```

#### Additional information
I've gotten Arduino Due with micro-ROS to work in Arduino IDE, and I've also done almost the exact same steps as above but with ESP32, and it worked. I did have to do some extra changes in the platformio.ini file for ESP32, but I don't know what to do this time.

**Comment by Acuadros95** [comment]
That error is caused by a compiler version mismatch ([Similar issue](https://stackoverflow.com/questions/54940410/gnu-toolchain-newlib-compatibility-between-toolchain-versions-undefined-symb)). We use the 4.8 version of `gcc-arm-embedded` to compile micro-ROS and platform IO uses 7.2.1, a newer and incompatible version which leads to this error.

You can modify the compiler version on your `platformio.ini` file adding this line:
```
platform_packages =
  ; use GCC AVR < 5.0
  toolchain-gccarmnoneeabi@<1.50000.0
```

**Comment by pnn16004** [comment]
Thank you very much! It works now.
