### ISSUE TITLE
Allow for different serial instances than the default Serial

### ISSUE THREAD

**Issue by markwomack** [micro-ROS/micro_ros_arduino#699]
Instead of assuming Serial for the transport, allow the serial instance to passed in as a pointer (HardwareSerial* ?), perhaps stored in the uxrCustomTransport as an optional member? (when null, then default to Serial)

https://github.com/micro-ROS/micro_ros_arduino/blob/fcc3b02fb76846fc8af1aceafe0a02fb9efac755/src/default_transport.cpp#L36

I am thinking of the multiple HardwareSerial instances (Serial1, Serial2, Serial3, etc) supported on many Arduino compatible microcontrollers (but most importantly the Teensy's, which I want to use :-)  I would like to attach micro-ROS to one of these serial ports instead of the main USB port so that I can use the main port for reprogramming.  I'm happy to make changes myself to support it, but would need some guidance on how to go about it the way you'd want it.

**Comment by pablogs9** [comment]
For sure that's possible, maybe you can start reading about the micro-ROS modular custom transports: https://micro.ros.org/docs/tutorials/advanced/create_custom_transports/

Let us know if you have problems or questions.
