### ISSUE TITLE
Performance with joy controller and twist messages to cmd_vel

### ISSUE THREAD

**Issue by igillespie** [micro-ROS/micro_ros_arduino#704]
## Issue template

- Hardware description: Arduino UDE
- Installation type: micro_ros_arduino
- Version or commit hash: galactic

This isn't so much as a bug report, but more of a performance issue I'm trying to resolve.

I have a Jetson Nano talking to an Arduino DUE. The Arduino DUE is running micro_ros_arduino and subscribes to twist messages from cmd_vel topic.

If I use teleop_twist_keyboard the twist messages are sent to the Arduino (and my robot wheels move) as expected. This works. But when I try to control through the joy stick, the micro_ros_agent can't seem to keep up with the all of the messages and I end up getting incredible lag between what I do on the joystick and what the motors on the robot do. I tried changing the /joy config 
so that autorepeat_rate is 0.0 and deadline is .2. I also set publisher depth to 10.

Anyone have any ideas on how I might reduce the lag time in my system?

Thanks for any help :-)

**Comment by pablogs9** [comment]
Which are the rates of `teleop_twist_keyboard` and your joystick?

**Comment by pablogs9** [comment]
Which are the rates of `teleop_twist_keyboard` and your joystick?

**Comment by pablogs9** [comment]
Which are the rates of `teleop_twist_keyboard` and your joystick?

**Comment by igillespie** [comment]
Thanks for the reply!

I'm launching teleop_twist_keyboard as a standalone node like this and just using the defaults:

`ros2 run teleop_twist_keyboard teleop_twist_keyboard`

When I try to get the params from that node, the system doesn't give me anything (no idea why). When I ask for the teleop_twist_joy_node params I get this:

`/teleop_twist_joy_node:
  ros__parameters:
    axis_angular:
      pitch: -1
      roll: -1
      yaw: 2
    axis_linear:
      x: 5
      y: -1
      z: -1
    enable_button: 7
    enable_turbo_button: 6
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    require_enable_button: true
    scale_angular:
      pitch: 0.0
      roll: 0.0
      yaw: 0.5
    scale_angular_turbo:
      pitch: 0.0
      roll: 0.0
      yaw: 4.0
    scale_linear:
      x: 0.5
      y: 0.0
      z: 0.0
    scale_linear_turbo:
      x: 4.0
      y: 0.0
      z: 0.0
    use_sim_time: false`

I'm still relatively new to ros, but I'm very psyched I've made it this far with micro-ros-arduino and ROS2 proper. 

Any ideas of what to try?

**Comment by pablogs9** [comment]
Could you try `ros2 topic hz [topic_name]` for both topics?

**Comment by igillespie** [comment]
I think these are the relevant topics/info you need (let me know if you need something else!)

CONTROLLING WITH JOYSTICK
Here ros2 topic hz /joy (I went forward several times, then went backward several times. Interestingly, the first few command with the joystick have manageable latency, but it seemed to get progressively worse and worse.)
 
average rate: 3.269
	min: 0.007s max: 1.939s std dev: 0.66712s window: 7
average rate: 3.207
	min: 0.006s max: 3.078s std dev: 0.80071s window: 18
average rate: 3.089
	min: 0.006s max: 3.078s std dev: 0.81456s window: 28
average rate: 3.498
	min: 0.006s max: 3.078s std dev: 0.76340s window: 43
average rate: 4.061
	min: 0.004s max: 3.078s std dev: 0.67761s window: 59
average rate: 4.282
	min: 0.004s max: 3.078s std dev: 0.63734s window: 71
average rate: 4.470
	min: 0.003s max: 3.078s std dev: 0.60852s window: 81
average rate: 4.585
	min: 0.003s max: 3.078s std dev: 0.58986s window: 92
average rate: 4.918
	min: 0.003s max: 3.078s std dev: 0.56482s window: 112
average rate: 4.778
	min: 0.003s max: 3.078s std dev: 0.56731s window: 116
average rate: 5.218
	min: 0.003s max: 3.078s std dev: 0.53444s window: 132
average rate: 5.095
	min: 0.003s max: 3.078s std dev: 0.53742s window: 138
average rate: 5.333
	min: 0.003s max: 3.078s std dev: 0.51704s window: 150
average rate: 5.204
	min: 0.003s max: 3.078s std dev: 0.52649s window: 160
average rate: 6.014
	min: 0.003s max: 3.078s std dev: 0.48554s window: 191
average rate: 5.470
	min: 0.003s max: 6.345s std dev: 0.62766s window: 212

Here is ros2 topic hz /cmd_vel when using the joystick to control

average rate: 3.267
	min: 0.008s max: 1.941s std dev: 0.66762s window: 7
average rate: 3.207
	min: 0.005s max: 3.077s std dev: 0.80069s window: 18
average rate: 3.089
	min: 0.005s max: 3.077s std dev: 0.81456s window: 28
average rate: 3.498
	min: 0.005s max: 3.077s std dev: 0.76344s window: 43
average rate: 4.061
	min: 0.003s max: 3.077s std dev: 0.67770s window: 59
average rate: 4.281
	min: 0.003s max: 3.077s std dev: 0.63750s window: 71
average rate: 4.470
	min: 0.003s max: 3.077s std dev: 0.60874s window: 81
average rate: 4.585
	min: 0.003s max: 3.077s std dev: 0.59008s window: 92
average rate: 4.918
	min: 0.003s max: 3.077s std dev: 0.56504s window: 112
average rate: 4.778
	min: 0.003s max: 3.077s std dev: 0.56751s window: 116
average rate: 5.218
	min: 0.003s max: 3.077s std dev: 0.53463s window: 132
average rate: 5.095
	min: 0.003s max: 3.077s std dev: 0.53760s window: 138
average rate: 5.333
	min: 0.003s max: 3.077s std dev: 0.51723s window: 150
average rate: 5.204
	min: 0.003s max: 3.077s std dev: 0.52663s window: 160
average rate: 6.014
	min: 0.003s max: 3.077s std dev: 0.48567s window: 191
average rate: 5.470
	min: 0.003s max: 6.346s std dev: 0.62778s window: 212

CONTROLLING WITH KEYBOARD
ros2 topic hz /cmd_vel
average rate: 1.627
	min: 0.601s max: 0.628s std dev: 0.01093s window: 3
average rate: 0.976
	min: 0.601s max: 2.255s std dev: 0.71015s window: 4
average rate: 0.778
	min: 0.601s max: 2.326s std dev: 0.82129s window: 5
average rate: 0.714
	min: 0.601s max: 2.326s std dev: 0.79231s window: 6
average rate: 0.712
	min: 0.601s max: 2.326s std dev: 0.73364s window: 7
average rate: 0.737
	min: 0.601s max: 2.326s std dev: 0.69782s window: 8
average rate: 0.832
	min: 0.545s max: 2.326s std dev: 0.69716s window: 10
average rate: 1.136
	min: 0.020s max: 2.326s std dev: 0.73312s window: 15
average rate: 1.047
	min: 0.020s max: 3.630s std dev: 0.95827s window: 18
average rate: 1.152
	min: 0.020s max: 3.630s std dev: 0.91266s window: 21
average rate: 1.031
	min: 0.020s max: 3.683s std dev: 1.05070s window: 23
average rate: 1.019
	min: 0.020s max: 3.683s std dev: 1.02992s window: 24
average rate: 0.853
	min: 0.020s max: 5.740s std dev: 1.37397s window: 25
average rate: 0.858
	min: 0.020s max: 5.740s std dev: 1.34765s window: 26
average rate: 0.830
	min: 0.020s max: 5.740s std dev: 1.33755s window: 27

**Comment by Acuadros95** [comment]
Hi, could you share your micro-ros code? 

Also, your agent output on debug move (`-v6` flag) could also be useful, so we can see the timing of the messages as they are sended and acknowledge by the board.

**Comment by igillespie** [comment]
There is a LOT of output from the agent. I'm attaching as a text file as it is too big for a comment. I'll upload my Arduino code next.

[micro_ros_agent_v6_log.txt](https://github.com/micro-ROS/micro_ros_arduino/files/7907588/micro_ros_agent_v6_log.txt)

**Comment by igillespie** [comment]
Arduino code:


```
#include <micro_ros_arduino.h>

#include <stdio.h>
#include <rcl/rcl.h>
#include <rcl/error_handling.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>

#include <geometry_msgs/msg/twist.h>
#include <std_msgs/msg/int32.h>

#include "TB66MotorController.h"

/*TEST*/
#include <Wire.h>
#include "SSD1306Ascii.h"
#include "SSD1306AsciiWire.h"

#define I2C_ADDRESS 0x3C
SSD1306AsciiWire oled;
// Define proper RST_PIN if required.
#define RST_PIN -1
/*END TEST*/

rcl_subscription_t subscriber;
geometry_msgs__msg__Twist msg;
rclc_executor_t executor;
rcl_allocator_t allocator;
rclc_support_t support;
rcl_node_t node;

rcl_timer_t tick_timer;
rcl_timer_t left_tick_timer;

rcl_publisher_t right_publisher;
std_msgs__msg__Int32 right_tick_msg;

rcl_publisher_t left_publisher;
std_msgs__msg__Int32 left_tick_msg;



//Define the Pins for Motors
//Motor 1
int pinAIN1 = 11; //Direction
int pinAIN2 = 8; //Direction
int pinPWMA = 3; //Speed

//Motor 2
int pinBIN1 = 12; //Direction
int pinBIN2 = 13; //Direction
int pinPWMB = 5; //Speed

//Standby
int pinSTBY = 7;

#define WHEEL_DIST 0.34 //is this distance of wheel to center or distance between wheels?


// Encoder output to Arduino Interrupt pin. Tracks the tick count.
// Other encoder output to Arduino to keep track of wheel direction
// Tracks the direction of rotation.
#define ENC_IN_RIGHT_A 28 //Yellow wire to motor
#define ENC_IN_RIGHT_B 29 //White wire to motor


#define ENC_IN_LEFT_A 30 //yellow
#define ENC_IN_LEFT_B 31 //white 


// Minumum and maximum values for 16-bit integers
const int encoder_minimum = -32768;
const int encoder_maximum = 32767;
 
// Keep track of the number of wheel ticks
volatile int left_wheel_tick_count = 0;
volatile int right_wheel_tick_count = 0;

// True = Forward; False = Reverse
boolean Direction_left = true;
boolean Direction_right = true;

// One-second interval for measurements
int interval = 1000;
long previousMillis = 0;
long currentMillis = 0;



long last_screen_update = 0;

TB66MotorController motorController(pinAIN1, pinAIN2, pinPWMA, pinBIN1, pinBIN2, pinPWMB, pinSTBY);


#define RCCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){error_loop();}}
#define RCSOFTCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){error_loop();}}

void setup()
{

  Serial.begin(115200);

  Wire.begin();
  Wire.setClock(400000L);

  pinMode(ENC_IN_LEFT_A , INPUT_PULLUP);
  pinMode(ENC_IN_LEFT_B , INPUT);
  pinMode(ENC_IN_RIGHT_A , INPUT_PULLUP);
  pinMode(ENC_IN_RIGHT_B , INPUT);
 
  // Every time the pin goes high, this is a tick
  attachInterrupt(digitalPinToInterrupt(ENC_IN_LEFT_A), left_wheel_tick, RISING);
  attachInterrupt(digitalPinToInterrupt(ENC_IN_RIGHT_A), right_wheel_tick, RISING);

#if RST_PIN >= 0
  oled.begin(&Adafruit128x64, I2C_ADDRESS, RST_PIN);
#else // RST_PIN >= 0
  oled.begin(&Adafruit128x64, I2C_ADDRESS);
#endif // RST_PIN >= 0

  oled.setFont(Adafruit5x7);

  oled.clear();
  oled.println("TR2 Ready!");
  
  set_microros_transports();
  allocator = rcl_get_default_allocator();

  RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));

  // create node
  RCCHECK(rclc_node_init_default(&node, "micro_ros_arduino_node", "", &support));

  // create subscriber
  RCCHECK(rclc_subscription_init_default(
    &subscriber,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Twist),
    "cmd_vel"));

  // create publisher right wheel
  RCCHECK(rclc_publisher_init_best_effort(
    &right_publisher,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int32),
    "right_tick_publisher"));

  // create publisher left wheel
  RCCHECK(rclc_publisher_init_best_effort(
    &left_publisher,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int32),
    "left_tick_publisher"));

  //  right timer,
  const unsigned int timer_timeout = 1000;
  RCCHECK(rclc_timer_init_default(
    &tick_timer,
    &support,
    RCL_MS_TO_NS(timer_timeout),
    timer_callback));

  RCCHECK(rclc_timer_init_default(
    &left_tick_timer,
    &support,
    RCL_MS_TO_NS(timer_timeout),
    left_timer_callback));

  // create executor 
  RCCHECK(rclc_executor_init(&executor, &support.context, 3, &allocator));
  RCCHECK(rclc_executor_add_subscription(&executor, &subscriber, &msg, &subscription_callback, ON_NEW_DATA));
  RCCHECK(rclc_executor_add_timer(&executor, &tick_timer));
  RCCHECK(rclc_executor_add_timer(&executor, &left_tick_timer));

  right_tick_msg.data = 0;
  left_tick_msg.data = 0;
}

void error_loop(){
  while(1){
    digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
    delay(750);
    digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
    delay(100);
    digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
    delay(100);
  }
}

void timer_callback(rcl_timer_t * timer, int64_t last_call_time)
{  
  RCLC_UNUSED(last_call_time);
  if (timer != NULL) {
    RCSOFTCHECK(rcl_publish(&right_publisher, &right_tick_msg, NULL));
    right_tick_msg.data = right_wheel_tick_count;
 
  }
}

void left_timer_callback(rcl_timer_t * timer, int64_t last_call_time)
{  
  RCLC_UNUSED(last_call_time);
  if (timer != NULL) {
    RCSOFTCHECK(rcl_publish(&left_publisher, &left_tick_msg, NULL));
    left_tick_msg.data = left_wheel_tick_count;
   
  }
}


float convertMotorMeterPerSecondToPWM(int wheel, float speed_in_m_per_s) {
  //128 = .55 for right, 
  //64 = .3
  //(128-64)/(.55-.3) = 256
  
  //left 128 = 0.51 
  //64 = .26
  //
  float returnValue = 0.;
  if (wheel == MOTOR_A) {
    returnValue = 245*speed_in_m_per_s;
  } else {
    returnValue = 251*speed_in_m_per_s;
  }
  return returnValue;
}

void subscription_callback(const void *msgin) {
  const geometry_msgs__msg__Twist * msg = (const geometry_msgs__msg__Twist *)msgin;

  
//  oled.clear();
//  oled.print("Received x:");
//  oled.println(msg->linear.x);
//
//  oled.print("Received y:");
//  oled.println(msg->linear.y);
//
//  oled.print("Received z:");
//  oled.println(msg->linear.z);

//  double vel = msg.linear.x;
//  double omega = msg.angular.z;
//  double r_omega = (vel + omega * WHEEL_DIST / 2) / WHEEL_RADIUS;
//  double l_omega = (vel - omega * WHEEL_DIST / 2) / WHEEL_RADIUS;
        
  float dx = msg->linear.x;
  float dr = msg->angular.z;

  float right = (dx + dr * WHEEL_DIST / 2.0);
  float left = (dx - dr * WHEEL_DIST / 2.0);
  
  right = convertMotorMeterPerSecondToPWM(MOTOR_A, right);
  left = convertMotorMeterPerSecondToPWM(MOTOR_B, left);
  
  long now = millis();
  if (now - last_screen_update > 1000) 
  {
    oled.clear();
    oled.print("motorA (l):");
    oled.println(left);
    oled.print("motorB (r):");
    oled.println(right);
    last_screen_update = millis();
  }
  if (right >= 0) {
    motorController.motorDrive(MOTOR_A, MOTOR_FORWARD, (right));
  } else {
    motorController.motorDrive(MOTOR_A, MOTOR_BACKWARD, (right*-1.0));
  }
  
  if (left >= 0) {
    motorController.motorDrive(MOTOR_B, MOTOR_FORWARD, (left));  
  } else {
    motorController.motorDrive(MOTOR_B, MOTOR_BACKWARD, (left*-1.0)); 
  }
  
}


// Increment the number of ticks
void right_wheel_tick() {
   
  // Read the value for the encoder for the right wheel
  int val = digitalRead(ENC_IN_RIGHT_B);
 
  if(val == LOW) {
    Direction_right = false; // Reverse
  }
  else {
    Direction_right = true; // Forward
  }
   
  if (Direction_right) {
     
    if (right_wheel_tick_count == encoder_maximum) {
      right_wheel_tick_count = encoder_minimum;
    }
    else {
      right_wheel_tick_count++;  
    }    
  }
  else {
    if (right_wheel_tick_count == encoder_minimum) {
      right_wheel_tick_count = encoder_maximum;
    }
    else {
      right_wheel_tick_count--;  
    }   
  }
}
 
// Increment the number of ticks
void left_wheel_tick() {
   
  // Read the value for the encoder for the left wheel
  int val = digitalRead(ENC_IN_LEFT_B);
 
  if(val == LOW) {
    Direction_left = true; // Reverse
  }
  else {
    Direction_left = false; // Forward
  }
   
  if (Direction_left) {
    if (left_wheel_tick_count == encoder_maximum) {
      left_wheel_tick_count = encoder_minimum;
    }
    else {
      left_wheel_tick_count++;  
    }  
  }
  else {
    if (left_wheel_tick_count == encoder_minimum) {
      left_wheel_tick_count = encoder_maximum;
    }
    else {
      left_wheel_tick_count--;  
    }   
  }
}
void loop()
{
  delay(100);
  RCCHECK(rclc_executor_spin_some(&executor, RCL_MS_TO_NS(100)));

}
```

**Comment by igillespie** [comment]
Well, when I pasted the code for the Arduino I saw the delay(100); I commented that out and it WORKS! 

I left it in there because it was in the micro_ros_publisher sample code, I figured it was important. 
I'd love to hear your thoughts on if the delay is important or not. I'm happy to close this too! THANK YOU again!

**Comment by Acuadros95** [comment]
That's great!
And don't worry about the delay, its not necessary at all.
