### ISSUE TITLE
How can I check or print log message (loginfo, logwarn, logerror...)

### ISSUE THREAD

**Issue by SeungRyeol** [micro-ROS/micro_ros_arduino#722]
## Issue template

- Hardware description: OpenCR 1.0
- RTOS: X
- Installation type: micro_ros_setup
- Version or commit hash: foxy

#### Expected behavior
1. print debug message to the terminal of micro_ros_agent node

#### Actual behavior
I didn't find the right way to print the log

#### Additional information

Like the code below, I tried to check the log through /rosout topic, but there was a problem that the board died during operation.

```c
#include <rcl_interfaces/msg/log.h>

...

rcl_publisher_t log_publisher;
rcl_interfaces__msg__Log log_msg;

...

  // create Log publisher
RCCHECK(rclc_publisher_init_default(
  &log_publisher,
  &node,
  ROSIDL_GET_MSG_TYPE_SUPPORT(rcl_interfaces, msg, Log),
  "rosout"
));

...

void publishLog(uint8_t level, char* name, char* msg){
  log_msg.level = level;
  log_msg.name.data = name;
  log_msg.name.size = strlen(log_msg.name.data);
  log_msg.msg.data = msg;
  log_msg.msg.size = strlen(log_msg.msg.data);

  struct timespec time_stamp = getTime();

  log_msg.stamp.sec = time_stamp.tv_sec;
  log_msg.stamp.nanosec = time_stamp.tv_nsec;

  RCSOFTCHECK(rcl_publish(&log_publisher, &log_msg, NULL));
}

```

**Comment by pablogs9** [comment]
micro-ROS does not implement a logging system by now. Using `rosout` is a good approach but you have to write your own logic. In any case, the micro-ROS agent won't print anything that is not related to XRCE communication.

Maybe this is a feature that we add to our roadmap.
