### ISSUE TITLE
Teensy 4.1 compilation error through PlatformIO

### ISSUE THREAD

**Issue by v-mifass** [micro-ROS/micro_ros_arduino#758]
## Issue template

- Hardware description: Teensy 4.1
- RTOS: Compiling on Win 10 -> Visual Studio Code -> PlatformIO
- Installation type: micro-ROS
- Version or commit hash: Current release (galactic 2.0.2)  (https://github.com/micro-ROS/micro_ros_arduino)

#### Steps to reproduce the issue
Following instructions on README.md

#### Expected behavior
Successful compilation

#### Actual behavior
Errors out looking for 'NativeEthernet.h', if copy that file from arduino library get other missing files (some in FNET/src)

#### Additional information
If I compile against Teensy36 compilation errors do not show

**Comment by pablogs9** [comment]
Which version of Arduino and Teensyduino do you have installed?

**Comment by pablogs9** [comment]
It seems that you need to install NativeEthernet library: [check here](https://github.com/vjmuzik/NativeEthernet)

**Comment by pablogs9** [comment]
Could you use the latest version of this repo in branch `galactic` instead of one of the releases?

**Comment by v-mifass** [comment]
Hmm so guess PlatformIO was too soft... adding 
lib_compat_mode = strict
Seemed to fix the library issue (default is 'soft')
