### ISSUE TITLE
Request to add std_srvs

### ISSUE THREAD

**Issue by SeungRyeol** [micro-ROS/micro_ros_arduino#784]
## Issue template

- Hardware description:  OpenCR 1.0 
- RTOS: Free RTOS
- Installation type: micro_ros_setup
- Version or commit hash: foxy

#### Expected behavior
I wish there was a **set_int.srv** or **set_float.srv** in std_srvs.
Users can make a custom service, but I think it would be very useful to use frequently, such as std_srvs/srv/set_bool.
Can you add the int or float type in std_srvs?

**Comment by pablogs9** [comment]
Hi, micro-ROS uses the default ROS 2 types, so I guess that this request should be made in the original `common_interfaces` repo: https://github.com/ros2/common_interfaces/tree/master/std_srvs/srv
