### ISSUE TITLE
question about rclc_executor_spin_period()

### ISSUE THREAD

**Issue by UncleMask** [micro-ROS/micro_ros_arduino#825]
hey!I tried to use `rclc_executor_spin_period()` to generate a 10ms period spin,but it gives a error info,shows below:

```
.pio\libdeps\teensy35\micro_ros_arduino\src\mk64fx512\fpv4-sp-d16-hard\libmicroros.a(librclc-sleep.c.obj): In function `rclc_sleep_ms':
sleep.c:(.text.rclc_sleep_ms+0x8): undefined reference to `usleep'
```

help me plz!

**Comment by pablogs9** [comment]
Basically, you do not have any `usleep` function. Implement it and the linker will resolve the symbols against the library:

```c
void
usleep(
  unsigned int us)
{
  delayMicroseconds(us);
}
```
