### ISSUE TITLE
micro_ros esp32 

### ISSUE THREAD

**Issue by Sarwan1494** [micro-ROS/micro_ros_arduino#911]
## Issue template

I have installed micro_ros_arduino using the include library option for version foxy. I am getting the following error while uploading the arduino code.  kindly inform how to solve this issue. 

![Screenshot from 2022-04-03 15-41-46](https://user-images.githubusercontent.com/88724213/161426248-7d133101-2950-4ee5-97dc-04ae52b2688a.png)

- Hardware description: esp32
- Installation type: micro_ros_arduino 
- Version or commit hash: foxy

**Comment by pablogs9** [comment]
@Acuadros95 can you take a look?

**Comment by Acuadros95** [comment]
Latest release `v2.0.4-foxy` worked right ahead for me.

Could you check your esp32 board package version? micro-ROS is supported on the latest version 2.0.2. 
Related: https://github.com/micro-ROS/micro_ros_arduino/issues/814

**Comment by Sarwan1494** [comment]
I updated the Arduino esp32 board package and it works fine. Thanks a lot
