### ISSUE TITLE
ESP32 WiFi / Serial connection problem

### ISSUE THREAD

**Issue by WhateverKatzenfutter** [micro-ROS/micro_ros_arduino#930]
## Issue template

- Hardware description: [ESP32](https://learn.adafruit.com/adafruit-huzzah32-esp32-feather)
- Installation type: Arduino IDE precompiled library
- Version or commit hash: [v2.0.4-galactic](https://github.com/micro-ROS/micro_ros_arduino/releases/tag/v2.0.4-galactic)  

#### Steps to reproduce the issue
- Follow the "How to use the precompiled library" instruction.
- Flash the micro-ros_publisher_wifi.ino on to the ESP32.
- Start micro ros agent via docker: docker run -it --net=host microros/micro-ros-agent:galactic udp4 -p 8888

#### Expected behavior
- ESP32 connects with the WiFi and establishes a connection with the micro ros agent.

#### Actual behavior
- ESP32 is connecting to the WiFi: 
![image](https://user-images.githubusercontent.com/73463846/162619971-5378c09c-a590-4492-8cf4-cc7242d3244c.png)

- No connection with the micro ros agent gets established:
![image](https://user-images.githubusercontent.com/73463846/162620019-4d59757d-d070-4446-8010-fcd50c7ed091.png)

#### Additional information
Hey guys, Iam pretty new to ROS at all and therefore not really sure if I got the installation steps right here, but I hope you can help me.

In the micro-ros_publisher_wifi.ino example for the set_microros_wifi_transports function Iam using the IP adress of my local machine where micro-ros agent is running via the docker and the port 8888, this should be right or?

![image](https://user-images.githubusercontent.com/73463846/162620173-d3a87d2d-6e46-4f90-980e-b28c2f28926b.png)

PS: Iam using Windows 10, should I better switch to Linux for this kind of work?

I also tried to get the connection to the agent via serial port, but it could not find the serial port and I am also not really sure, if Iam using the right device name for the docker command: 

docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:galactic serial --dev [YOUR BOARD PORT] -v6

![image](https://user-images.githubusercontent.com/73463846/162628158-edfb9247-a4e0-4682-a1ab-e6638101a68e.png)
![image](https://user-images.githubusercontent.com/73463846/162628176-59cf3a4f-73ad-45e8-902c-4770a5152857.png)

What would be the right port of my board?

**Comment by Acuadros95** [comment]
> PS: Iam using Windows 10, should I better switch to Linux for this kind of work?

Yes, micro-ROS agent doesnt support serial transport on Windows, the wifi problems may also be related to docker issues with windows. Can you try on Linux?

Anyway, check the network traffic with wireshark or similar. The esp32 should send a periodic message trying to init a session to the configured Agent IP and port.

**Comment by WhateverKatzenfutter** [comment]
Thanks for the idea to check the network traffic, but I think I will just switch to Linux and report back, if there are still some problems.
