### ISSUE TITLE
line order of generated files

### ISSUE THREAD

**Issue by amilcarlucas** [micro-ROS/micro_ros_arduino#932]
## Issue template

- Hardware description: Arduino Portenta
- RTOS: Mbed
- Installation type: node, using micro_ros_arduino directly
- Version or commit hash: latest galactic

#### Steps to reproduce the issue
Just compile it using the instructions on the README.md file

#### Expected behavior
The generated `available_ros2_types` and `build_packages` files should a bit bit similar to the ones checked in at the git repository.

#### Actual behavior
The lines in the new generated files are out of order, comparing with the repository files is very hard

#### Additional information
It should either:
* produce a reproducible output order,
* or sort the files (during or after generation)

This way comparing with the repo is straightforward

**Comment by pablogs9** [comment]
That's a known issue, we do not have yet a way of producing a reproducible order. Please PR if you have any solution in mind.

**Comment by amilcarlucas** [comment]
done and tested
