### ISSUE TITLE
Message dropping for subscribers

### ISSUE THREAD

**Issue by ajaykumar666** [micro-ROS/micro_ros_arduino#983]
## Issue template

- Hardware description: STM32F412VGT custom board
- Version or commit hash: microROS Arduino foxy

I have 4 publishers for sensors and 2 subscribers for motors. When running the bot there are messages dropping for subscribers causing the bot to move irregularly. I tried different QOS profiles in qos_profile.h but things didn't improve. Is there any way to solve this?

**Comment by pablogs9** [comment]
Please provide instructions for replicating this issue: procedure for building the application for STM32F412VGT (as it is not a micro-ROS for Arduino supported platform) code, ROS 2 types, configuration, meta files...

**Comment by ajaykumar666** [comment]
the controller uses Arduino/libraries/micro_ros_arduino-foxy/src/cortex-m4/fpv4-sp-d16-hard precomplied library. all that is needed is to use STM32duino board manager in arduino.


`#include "config.h"
#include "BotState.h"
#include "Motors.h"
//#include "usSensor.h"
#include "Clutch.h"
#include "imuSensor.h"

#include <micro_ros_arduino.h>
#include <stdio.h>
#include <rcl/rcl.h>
#include <rcl/error_handling.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include <rmw_microros/rmw_microros.h>

#include <sensor_msgs/msg/range.h>
#include <std_msgs/msg/int16.h>
#include <std_msgs/msg/int32.h>
#include <std_msgs/msg/u_int8.h>
#include <std_msgs/msg/float32_multi_array.h>
#include <std_msgs/msg/u_int8_multi_array.h>

rcl_publisher_t imu;
std_msgs__msg__Float32MultiArray msgImu;

//rcl_publisher_t us;
//std_msgs__msg__UInt8MultiArray uscan;


rcl_publisher_t lwheel_encoder;
std_msgs__msg__Int32 lwheel_int;

rcl_publisher_t rwheel_encoder;
std_msgs__msg__Int32 rwheel_int;

//rcl_publisher_t clutch_state_fb;
//std_msgs__msg__UInt8 clutch_state_int;

rcl_subscription_t lmotor_cmd;
std_msgs__msg__Int16 ltspeed;

rcl_subscription_t rmotor_cmd;
std_msgs__msg__Int16 rtspeed;

//rcl_subscription_t clutch_state;
//std_msgs__msg__UInt8 cstate;

rclc_executor_t executor;
rclc_support_t support;
rcl_allocator_t allocator;
rcl_node_t node;
rcl_timer_t timer;
rcl_timer_t us_timer;
rcl_ret_t temp_rc;

#define RCCHECK(fn) {  temp_rc = fn; if((temp_rc != RCL_RET_OK)){error_loop();}}

int break_count = 0;

bool micro_ros_init_successful;

void error_loop() {
  while (1) {
    delay(100);
    Serial.println("ERROR!!!");
    Motors::breakMotors();
    HAL_NVIC_SystemReset();
  }
}

void timer_callback(rcl_timer_t * timer, int64_t last_call_time)
{
  (void)last_call_time;
  if (timer != NULL) {
    //    rcl_publish(&clutch_state_fb, &clutch_state_int, NULL);
    rcl_publish(&lwheel_encoder, &lwheel_int, NULL);
    rcl_publish(&rwheel_encoder, &rwheel_int, NULL);
//    rcl_publish(&us, &uscan, NULL);
    rcl_publish(&imu, &msgImu, NULL);

//    usSensor::updateState();
    Motors::updateState();
    //    Clutch::updateState();
    imuSensor::updateState();

    lwheel_int.data = Motors::get_motors_pulse1();
    rwheel_int.data = Motors::get_motors_pulse2();
    //    clutch_state_int.data = Clutch::isEngaged;

//    uscan.data.data = usSensor::distance;
    msgImu.data.data = imuSensor::imu_out;
  }
}

void lcmdVelCB(const void * msgin)
{
  const std_msgs__msg__Int16 * ltspeed = (const std_msgs__msg__Int16 *)msgin;
  Motors::lMotor(ltspeed->data);
//  Serial.print(ltspeed->data);
//  Serial.print(", ");
}

void rcmdVelCB(const void * msgin)
{
  const std_msgs__msg__Int16 * rtspeed = (const std_msgs__msg__Int16 *)msgin;
  Motors::rMotor(-rtspeed->data);
//  Serial.println(rtspeed->data);

}

//void clutchState(const void * msgin)
//{
//  const std_msgs__msg__UInt8 * cstate = (const std_msgs__msg__UInt8 *)msgin;
//  if (cstate->data == 1 && Clutch::isEngaged == 0) Clutch::toggleClutch();
//  if (cstate->data == 0 && Clutch::isEngaged == 1) Clutch::toggleClutch();
//}

void create_entities()
{
const rmw_qos_profile_t * qos_profile = &rmw_qos_profile_parameters; //rmw_qos_profile_sensor_data;
  allocator = rcl_get_default_allocator();

  //create init_options
  RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));

  // create node
  RCCHECK(rclc_node_init_default(&node, "micro_ros_arduino_node", "", &support));

  // create publisher
  RCCHECK(rclc_publisher_init_default(
            &imu,
            &node,
            ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Float32MultiArray),
            "imu"));

//  RCCHECK(rclc_publisher_init_default(
//            &us,
//            &node,
//            ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, UInt8MultiArray),
//            "us_scan"));

  RCCHECK(rclc_publisher_init(
            &lwheel_encoder,
            &node,
            ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int32),
            "lwheel_encoder",
            qos_profile));

  RCCHECK(rclc_publisher_init(
            &rwheel_encoder,
            &node,
            ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int32),
            "rwheel_encoder", 
            qos_profile));

  //  RCCHECK(rclc_publisher_init_default(
  //            &clutch_state_fb,
  //            &node,
  //            ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, UInt8),
  //            "clutch_state_fb"));

  // create subscriber
  RCCHECK(rclc_subscription_init_default(
            &lmotor_cmd,
            &node,
            ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int16),
            "lmotor_cmd"));

  RCCHECK(rclc_subscription_init_default(
            &rmotor_cmd,
            &node,
            ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Int16),
            "rmotor_cmd"));

  //  RCCHECK(rclc_subscription_init_default(
  //            &clutch_state,
  //            &node,
  //            ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, UInt8),
  //            "clutch_state"));

  // create timer,
  const unsigned int timer_timeout = 20;
  RCCHECK(rclc_timer_init_default(
            &timer,
            &support,
            RCL_MS_TO_NS(timer_timeout),
            timer_callback));

  // create executor
  RCCHECK(rclc_executor_init(&executor, &support.context, 7, &allocator));
  RCCHECK(rclc_executor_add_timer(&executor, &timer));
  RCCHECK(rclc_executor_add_subscription(&executor, &rmotor_cmd, &rtspeed, &rcmdVelCB, ON_NEW_DATA));
  RCCHECK(rclc_executor_add_subscription(&executor, &lmotor_cmd, &ltspeed, &lcmdVelCB, ON_NEW_DATA));
  //  RCCHECK(rclc_executor_add_subscription(&executor, &clutch_state, &cstate, &clutchState, ON_NEW_DATA));

  micro_ros_init_successful = true;
}

void destroy_entities()
{
//  rcl_publisher_fini(&us, &node);
  //  rcl_publisher_fini(&clutch_state_fb, &node);
  rcl_publisher_fini(&lwheel_encoder, &node);
  rcl_publisher_fini(&rwheel_encoder, &node);
  rcl_publisher_fini(&imu, &node);
  rcl_subscription_fini(&lmotor_cmd, &node);
  rcl_subscription_fini(&rmotor_cmd, &node);
  //  rcl_subscription_fini(&clutch_state, &node);
  rcl_node_fini(&node);
  rcl_timer_fini(&timer);
  rclc_executor_fini(&executor);
  rclc_support_fini(&support);

  micro_ros_init_successful = false;
}

void setup() {
//  Serial.begin(9600);
  set_microros_transports();
//  usSensor::initusSensor();
  Motors::initMotors();
  Clutch::initClutch();
  imuSensor::initImu();

//  uscan.data.capacity = 6;
//  uscan.data.size = sizeof(usSensor::distance) / sizeof(uint8_t);
//  uscan.data.data = (uint8_t*) malloc(uscan.data.capacity * sizeof(uint8_t));
//
//  uscan.layout.dim.capacity = 0;
//  uscan.layout.dim.size = 0;
//  uscan.layout.dim.data = (std_msgs__msg__MultiArrayDimension*) malloc(uscan.layout.dim.capacity * sizeof(std_msgs__msg__MultiArrayDimension));


  msgImu.data.capacity = 9;
  msgImu.data.size = sizeof(imuSensor::imu_out) / sizeof(float);
  msgImu.data.data = (float*) malloc(msgImu.data.capacity * sizeof(float));

  msgImu.layout.dim.capacity = 0;
  msgImu.layout.dim.size = 0;
  msgImu.layout.dim.data = (std_msgs__msg__MultiArrayDimension*) malloc(msgImu.layout.dim.capacity * sizeof(std_msgs__msg__MultiArrayDimension));

  micro_ros_init_successful = false;
//    ct = millis();
}

void loop() {
  //  Serial.println("Loop");

  if (RMW_RET_OK == rmw_uros_ping_agent(50, 2))
  {
    //    Serial.println("Agent found");
    if (!micro_ros_init_successful) {
      create_entities();
    } else {
      //      Serial.println("Spinning");
      rclc_executor_spin_some(&executor, RCL_MS_TO_NS(2));
    }
  }
  else if (micro_ros_init_successful)
  {
    //    Serial.println("Agent lost");
    Motors::breakMotors();
    destroy_entities();
  }
  //  Serial.println(millis()-ct);
}`

**Comment by ajaykumar666** [comment]
Imu and encoders are being subscribed at 50hz
While motor commands are being published at 20 hz on Ros side

**Comment by pablogs9** [comment]
Could you check if this works as expected not pinging the agent, something like:

```c
void setup() {
...
      create_entities();
...
}

void loop() {
rclc_executor_spin_some(&executor, RCL_MS_TO_NS(2));
}
```

Another interesting check would be to create the entities in best effort. This is using `rclc_*_init_best_effort` instead of `rclc_*_init_default`.

Those two changes will reduce the number of messages on the wire (in this case a serial port), allowing the transfer of more data payloads. This is a 115200 bauds serial port, probably the loss of some packages is due to the bandwidth available.

Finally, if the two options above do not work, I would try reducing the rate of the publications and subscriptions to fit the bandwithd of the transport layer (aprox 115 kbps),

**Comment by ajaykumar666** [comment]
As for the baudrate, I have already increased it to 460800 so as to create a bigger bandwidth. I'll try to reduce the frequency of publishing and rcl_init_best_effort.

**Comment by ajaykumar666** [comment]
thanks for the help. it was fixed by changing some frequencies for publishers and subscribers.

**Comment by ajaykumar666** [comment]
As for the baudrate, I have already increased it to 460800 so as to create
a bigger bandwidth. I'll try to reduce the frequency of publishing and
rcl_init_best_effort.
